### ISSUE TITLE
Parse the HTML page

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#102]
We've gotten some HTML samples [here](https://drive.google.com/drive/u/0/folders/0B6pJr3rz2MCGZjFmQlhBdk1yb3c)
We need to get the parsed context from the HTML code, e.g., title, date, content, source, etc.

We should use some open source tools which ideally has Apache License.

@dennis09121111 @alberttv

**Comment by dennis09121111** [comment]
Steps:
- [ ] Recognize the `state`s that contains the actual alerts.
- [ ] From the candidate web page to parse the useful text field from the HTML
- [ ] Deeper analysis to get the event name, author, place, time or some other NEs from the text.
