### ISSUE TITLE
study how the NewsStand project collected news articles and geotagged them

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#121]
http://www.cs.umd.edu/~hjs/
http://newsstand.umiacs.umd.edu/web/
http://dl.acm.org/citation.cfm?doid=1463434.1463458

**Comment by kaiyim** [comment]
NewsStand uses a large set of RSS feeds as its primary source of data. RSS is a widely-used XML protocol for online publication and is ideal for NewsStand, as it requires at least a title, short description, and web link for each published news item. To retrieve a new story, NewsStand collect the story metadata from the RSS feed, and download the story webpage using the provided web link. NewsStand maintains a list of active RSS feeds, scans the feed periodically, and downloads new contents automatically. 
The RSS feed sources are not mentioned in the paper.

**Comment by kaiyim** [comment]
To geotag the location in the news article, NewsStand uses a statistical NLP method to identify phrases from the article that correspond to location, and stores as geographic features of the entity feature vector. The tool they use is NE tagger of the LingPipe toolkit. 
Then they use a database of geographical locations to find those geographic features that are names of actual locations. The database they use is based on GeoNames database, which contains over 6.5 million geographic locations, and over 8 million location names from around the world.
Each geographic feature may match multiple entries in the geographical location, thus disambiguation is required. They use multiple heuristics to score each geographic feature, which is discussed in section 5.3.
To determine the geographic focus of the news story, NewsStand score the georeferences by frequency and it's place of appearance(score higher in the beginning of the article or in the title).

**Comment by chenlica** [comment]
Thanks for the great summary.  I will close this issue.
