### ISSUE TITLE
Supporting aggregation views

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#174]
The sub-set views works OK now. We want to keep those aggregation views.

**Comment by hh1680651** [comment]
Back-end:

- Change relative queries (Filter & Create).
- Create table without keywords (JSONParser.scala).

Front-end:

- Send initial request for the whole map.
- Send further request.
- Solve city request's problem.

**Comment by baiqiushi** [comment]
For example, a heatmap can benefit from such a view. (i.e. results group by cells)

**Comment by chenlica** [comment]
Will do in the future.
