### ISSUE TITLE
Extend the UI for different countries

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#178]
... e.g. Brazil, South American, or even globally. 

It requires the choropleth shape files.

**Comment by JavierJia** [comment]
@MoniMoledo I think you may want to start with this issue first? 
It should not require many changes but requires you to set up the AsterixDB cluster and the current UI on it.

I would suggest the following steps:
- [ ] set up the AsterixDB cluster. 
Ideally, there should be multiple machines used for storage and computation. You can follow the [AsterixDB documentation](https://ci.apache.org/projects/asterixdb/install.html) to set up the cluster. 
- [ ] find the South American shape files. 
Ideally, it should be similar with the GeoJSON files in `neo/public/data`. However, usually, the raw data are not that friendly. Likewise, for U.S. data we are using the `edu/uci/ics/cloudberry/gnosis/USHierarchyBuilder.scala` to convert the raw data in `gnosis/src/main/resources/raw` to a uniformed GeoJSON format. You can update the corresponding logic to work out your data. 
- [ ] update the `edu/uci/ics/cloudberry/noah/feed/tagTweet.scala` to tag tweets using the South American GeoJSON files.
- [ ] ingest the tweets by using the `streamFeed.sh` in the codebase. you may also need the [ddl.aql](https://gist.github.com/JavierJia/9ed7744c938c5cb66aba63007b86a987) and [livefeed.aql](https://gist.github.com/JavierJia/565cefd9322df35c7abeefbfcfcee9f8).
- [ ] in `neo/public/javascripts/map/controllers.js` you can let it load your GeoJson files and update the map center in `neo/views/index.scala.html`.
- [ ] in `neo/application.conf` you can update the `asterixdb.url` to your server.

Then everything should be OK to go. 😄

**Comment by MoniMoledo** [comment]
Great! Thank you for the steps!! I am going to start setting up the environment in the lab next week. Keep you posted.

**Comment by chenlica** [comment]
👍

**Comment by MoniMoledo** [comment]
Final Project Plan: https://docs.google.com/document/d/16tS-tEiJ_aDbI7JV_KD8VzNnw104vikRPCfTdfUoWn8/edit

**Comment by chenlica** [comment]
Since I couldn't leave comments on the google doc, let me leave them on this ticket.  Those tasks look great!  It will be good to put some estimated amount of time for each task for better planning.  I would be very impressed if those tasks can be finished within one semester :-)
