### ISSUE TITLE
Implement the Lookup statement

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#194]
There are some missing features in the AQLGenerator. The most important one is the `lookup` statement. 

Here is one example 

```
    { "dataset":"twitter",
      "lookup": [{
          "joinKey":"geo.city",
          "dataset":"US_population",
          "lookupKey":"city",
          "select":"population",
          "as" : "us_population"
},
         {
          "joinKey":"geo.city",
          "dataset":"tweet_user",
          "lookupKey":"city",
          "select":"population"}
],
      "filter":[
        { "field":"create_at", 
          "relation":"inRange",    
          "values":["11-01-2016","11-08-2016"]},
        { "field":"text",
          "relation":"contains",
          "values":["zika","virus"]}],
      "group":{
        "by":[
           {"field":"geo.state", "as" : "state"],
        "aggregate":[
           { "field": "*", "apply": "count"}
           { "field": "population", "apply": "sum", 
             "as":"population"}]}}]
  }
```
In this example, we lookup the `US_population` dataset and join two dataset with the condition of `twitter.geo.city = US_population.city` and only append the `population` field to the current dataset (`twitter`)

Finally, it will group the records to different states. Within each group, it can apply the `count` for `*` field as usual. Plus, it can also apply the `sum` function on the newly appended `population` field.

**Comment by JavierJia** [comment]
We use the Play JSON library to parse the JSON to the Query object. You can find the corresponding document [here](https://www.playframework.com/documentation/2.5.x/ScalaJson#Json)

**Comment by JavierJia** [comment]
- [ ] Translate the lookup JSON to lookup Scala query object. You can start from the `JSONParser` and its test. 
- [ ] Generate the Twitter user data and test the actual performance of lookup

**Comment by nishadg** [comment]
Link to wiki : https://github.com/ISG-ICS/cloudberry/wiki/Lookup-Functionality
