### ISSUE TITLE
Improve the Noah feed adapter 

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#195]
... to make the reingestion work easier. 

In `edu/uci/ics/cloudberry/noah/feed/TwitterFeedStreamDriver.java`, we store the original tweet json file. To re-ingest the data, we need to call the `geotag.sh` to tag the file to ADM format and then send to *DB file feed.

To make the reingestion work easier, we can make a `socket feed` which is reading the stored (but not yet ingested datafile) json file first, at the same time, we should accumulate the online tweets somewhere. When the historical data has been ingested, we can resume to the normal online only feed status.

**Comment by xizzzz** [comment]
https://github.com/xizzzz/docker-kafka
