### ISSUE TITLE
Showing boundaries of upper-level polygons on map

### ISSUE THREAD

**Issue by zonghengma** [ISG-ICS/cloudberry#219]
The front-end should show the boundaries of current level polygons, and upper-level polygons in a different color. 

Result should be similar to  this:
![555px-2012_presidential_election_by_county svg](https://cloud.githubusercontent.com/assets/7375243/20123755/4827c282-a5d6-11e6-9c74-bb1239372f3a.png)

**Comment by chenlica** [comment]
It looks beautiful!  Similar to those maps on the Election Day :-)

**Comment by zonghengma** [comment]
This issue is solved and the code is added to PR #214
