### ISSUE TITLE
Front-end cache

### ISSUE THREAD

**Issue by zonghengma** [ISG-ICS/cloudberry#222]
Currently, when the map is dragged, the entire query data will be reloaded. Need to implement a way to store the query results, if the map is dragged back to an area that has been viewed before, the front-end will load the data immediately without sending new queries.

**Comment by chenlica** [comment]
I had exactly the same idea!  It can make the frontend much more friendly.

**Comment by zonghengma** [comment]
I have a brief googledoc explaining my current idea on caching [here](https://docs.google.com/a/uci.edu/document/d/1NuemR85hfaxs86CEiygww_CICE6gins7IAJdf3gTAjQ/edit?usp=sharing)

**Comment by vidhya567** [comment]
These are MDN pages for service worker and IndexedDB caching techniques
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

**Comment by vidhya567** [comment]
@zonghengma Can You allow access to read the google doc?

**Comment by zonghengma** [comment]
@vidhya567 I've granted access for you to edit and view. Sorry for the delay.

**Comment by vidhya567** [comment]
Now we are able to cache the http requests(bounds) and responses using PouchDB.Also we found the maximum intersecting cache bound and the current request bound.With that we are able to find the responses(polygon data) that is already in cache and we are able to give that as response for current response.We are using Turf API's turf.intersect and turf.difference methods

**Comment by vidhya567** [comment]
Have to find a way to tackle the difference part! Our middleware wont accept polygons,only rectangles. But Asterix DB can accept it.

**Comment by vidhya567** [comment]
Currently the cache has 3 fields 
id - request (bounds)
features - responses for that request consisting of polygon features
zoom level-maps zooming level

**Comment by vidhya567** [comment]
Apparently zoom level is of no use .Same level zooms doesn't provide that much intersection between polygons. The polygons for the responses are found by seeing whether their center is within the area of intersection.Surprisingly most of features(polygons) needed are already in the cache.Obviously,The difference part is very less in very frequently visited cities.

**Comment by vidhya567** [comment]
We have now removed pouch DB.We are using rBush Tree now to cache all the polygons.
