### ISSUE TITLE
Move the UI components from the current cloudberry ui to play branch

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#23]
Including
- [x] Map
- [x] Timeline
- [x] HashTag
- [x] Actual Tweets.

**Comment by JavierJia** [comment]
@JeremyLi28 could you list the rest of the work mentioned in the #27  to here? thank you!

**Comment by JeremyLi28** [comment]
TODO:
1. Add the actual tweets.
2. Further Modulize for sidebar
3. Some styling issues
4. (Long term) Develop for general purpose.
