### ISSUE TITLE
Replace the actor message passing in TweetMap demo by using "/berry" http request

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#230]
Currently, in the front-end server, the `NeoActor` is sending the message directly to the `berryClient`. It works because the front-end and the middleware live in the same server which will not be the case if we want to make Cloudberry a general purpose middleware. 

Now, since we have the `/berry` API, the `NeoActor` should send an HTTP request to `http://hostname:port/berry` instead of an actor message and then receive a stream of HTTP chunked results.

You can read this [documentation](https://www.playframework.com/documentation/2.5.x/ScalaWS#Processing-large-responses) about how to use it to handle a stream of responses.

**Comment by JavierJia** [comment]
@haochen07

**Comment by JavierJia** [comment]
You can start from the non-streaming fashion first. :-)

**Comment by haochen07** [comment]
This Issue is done. Do I need to close it ? @JavierJia

**Comment by JavierJia** [comment]
please do 📪

**Comment by haochen07** [comment]
which means close it ?

**Comment by JavierJia** [comment]
haha, yes, please feel free to close it.
