### ISSUE TITLE
Create a NewYorkGnosis object to resolve the geographic queries

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#24]
We have the `USGeoGnosis` in the `gnosis` module. It is used by `noah` and `neo` for the purposes of geotagging data source and geotagging the box area from the query. 
We need a similar component and functionality to handle the NewYork data.

**Comment by JavierJia** [comment]
@xixZ Could you also tag the pick-up position? we will need both tagged information.

**Comment by xixZ** [comment]
Already tagged.

**Comment by JavierJia** [comment]
nice.
