### ISSUE TITLE
TODO: Add TwitterMap front-end test

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#25]

**Comment by JavierJia** [comment]
@JeremyLi28 It seems I still need a lot of time for the middleware code. It will be very nice that you can have a try about adding the test for front-end. Also I'm not very sure how to integrate the test for Play and Angular. [Here](https://www.playframework.com/documentation/2.5.x/ScalaFunctionalTestingWithSpecs2#WithBrowser) is the document about the Play UI test.

**Comment by JavierJia** [comment]
Should use [phantomjs ](http://phantomjs.org/) to implement the frontend test in order to make the test run on travis.

**Comment by baiqiushi** [comment]
We should consider it when do front-end refactoring.

**Comment by chenlica** [comment]
Will do in the future.
