### ISSUE TITLE
Adjust the timeline position on the TwitterMap

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#254]
The timeline component is blocked if the resolution is lower. 
We should adjust the timeline width to a relative number to show it on a smaller resolution screen.

A quick way to debug the behavior is to use the Chrome dev tool to [adjust the webpage size](https://developers.google.com/web/tools/chrome-devtools/device-mode/emulate-mobile-viewports).

**Comment by HotLemonJuice** [comment]
okay, I'm on it.
