### ISSUE TITLE
Neo should cancel the previous query if new query comes

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#265]
Previously, we are using one BerryClient to answer one specific NeoActor. In that case, whenever there is a new request, the berryClient will return to the initial status. E.g., a user may ask "zika", before the entire timeline finishes, he may get bored and ask a new one, say "flood". The "zika" related result won't be returned.

However, since we are using the web socket connection with BerryClient, each query will be connected with different BerryClient!! So the previous working BerryClient won't notice that the request has changed. It will keep sending the old result. As the result, for the aforementioned scenario, the current online demo will return the mixed results for both queries❗️ 

A simple fix might be canceling the previous `Batch` request. Some examples from StackOverflow: http://stackoverflow.com/questions/16009837/how-to-cancel-future-in-scala

A more sophisticated solution is that we should design a `cancel` protocol between clients and berryClient.

**Comment by chenlica** [comment]
Who should be the right person to do the fix?  @haochen07 ?

**Comment by JavierJia** [comment]
Yes, I would encourage Hao to have a try 😄

**Comment by haochen07** [comment]
Ok I'll try to fix that

**Comment by JavierJia** [comment]
As we discussed today, we will directly remove the `NeoActor` and only use the `ws` API to communicate with front-end.

**Comment by haochen07** [comment]
OK
