### ISSUE TITLE
Refactor Cloudberry Query-related code to use typed fields

### ISSUE THREAD

**Issue by luochen01** [ISG-ICS/cloudberry#268]
Current, the `Query` class uses field names (with string type) to refer fields. For example, the definition of `FilterStatement` is
```
case class FilterStatement(field: String,
                           funcOpt: Option[TransformFunc],
                           relation: Relation,
                           values: Seq[Any]) extends Statement {
```

This imposes several problems on the subsequent use of the field, since one has to manually lookup from the schema to get the typed field, which could be tedious.

Thus, it's better to refactor query-related code to use typed fields. The expected main changes as follows:

- In the query-related classes, we need to replace the string field with a typed field (with `Field` type). This could result in a lot of changes in the codebase which uses the query-related objects.
- `JsonParser` should resolve the fields from string field names, and validate the user-submitted query (from json objects), and return a query which contains typed fields.

**Comment by JavierJia** [comment]
Can we keep the `JSONParser` and let the resolving and validating be the internal functions of it? 
I think the `QueryResolver` and `Validator` should only be used once inside the parser.

**Comment by luochen01** [comment]
Yes, `QueryResolver` and `Validator` will be inside `JsonParser`. My initial thought is that it would be cleaner for `JsonParser` if we create the `UnresolveQuery` first and then resolve it using `QueryResolver`, rather than mixing up everything (json parsing, field resolving and query validating) within the same `JsonParser`.

**Comment by chenlica** [comment]
Good job!
