### ISSUE TITLE
Represent Tweets Using Dots on the Map

### ISSUE THREAD

**Issue by HotLemonJuice** [ISG-ICS/cloudberry#274]
So far we are using a heat map to show the Tweets on the map. It is a high-level description of the data.

Now if we can show the exact location of each Tweet, we can make the connection between the data and the geolocation closer.

A good example by MapD:
https://www.mapd.com/demos/tweetmap/
![screen shot 2017-03-06 at 16 41 41](https://cloud.githubusercontent.com/assets/12385178/23636764/389961c8-028c-11e7-92f1-d80b57434ac0.jpg)

However, since there are too much data to load in the browser, we need use some tricks to avoid crashing the browser. We can start implementing this feature in small areas of the map, e.g. city level.

**Comment by chenlica** [comment]
@HotLemonJuice Good luck and have fun! :-)
