### ISSUE TITLE
TODOs (for our records)

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#278]
1. Work on open issues 
1. Try other frontend (e.g., Vega, Tableau, [ParaView](http://www.paraview.org/), [SuperSet](https://github.com/airbnb/superset) )
1. Try other backend (e.g., MongoDB, Druid)
1. Rebuild the current demo using other solutions, e.g., Mongo, Spark (for comparison purposes)
1. Integrate Flickr image with TwitterMap #34 
1. Approximate Answering using Stats
1. Support continuous query ( in a space of the middleware)
1. Middleware cache 
1. High available middleware cluster
1. Stress test of the cluster using a high-ingestion rate.
1. Evaluate http://nanocubes.net/ (from AT&T)
1. Read the paper titled "I4E: interactive investigation of iterative information extraction" at http://dl.acm.org/citation.cfm?doid=1807167.1807253

Some ongoing work
* Implement the Aggregation views
* Sentiment analysis for the restaurant domain

**Comment by JavierJia** [comment]
* Integrate Flickr image with TwitterMap #34 
* Approximate Answering using Stats
* Support continuous query ( in a space of the middleware)
* Middleware cache 
* High available middleware cluster

Some ongoing work
* Implement the Aggregation views
* Support corellation analytics on Twitter

**Comment by baiqiushi** [comment]
Archive this and close it.

**Comment by baiqiushi** [comment]
Archived to this [blog](https://cloudberry-uci.blogspot.com/2018/01/todos-mar-13-2017.html)
