### ISSUE TITLE
Refactor AQLGenerator to be consistent with the current class Hierarchy

### ISSUE THREAD

**Issue by luochen01** [ISG-ICS/cloudberry#285]
Current, we have another query generator, namely `SQLPPGenerator`, and `AsterixQueryGenerator` as the base class for asterixdb-related queries. Thus, it's desirable to unify `SQLPPGenerator` and `AQLGenerator` to make them more consistent and unified.

**Comment by JavierJia** [comment]
we can just remove the `AQLGenertor` later.
