### ISSUE TITLE
Integrate with SparkSQL

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#287]
E.g., SparkSQL and MongoDB.

We will need to write the specific connector for both systems and try to compare the performance to using different DB systems.

As @luochen01 suggest, we will start from implementing the SparkSQL connector first. :-)

**Comment by JavierJia** [comment]
@ sicong

**Comment by chenlica** [comment]
What's the github id of Sicong?

Sicong, to keep the momentum of the work, please do it at your earliest convenience.

**Comment by chenlica** [comment]
BTW, welcome aboard!

**Comment by JavierJia** [comment]
@lsclovecode
