### ISSUE TITLE
Update the text index type to full-text index

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#300]
Previously, we were using the `text` index. As @waans11  implemented the full-text search feature in the newest AsterixDB, we need to build the full-text index and update the AQLGenerator and the SQLPPGenerator to accommodate the new searching syntax.

**Comment by JavierJia** [comment]
The code is here: `zion/src/main/scala/edu/uci/ics/cloudberry/zion/model/impl/AsterixQueryGenerator.scala` `parseTextRelation`.

**Comment by JavierJia** [comment]
To use the `full-text` search, we will need to create a full-text index. In the xxx
 we will need to update this line 
`create index text_idx if not exists on ds_tweet("text") type keyword;`
to
`create index text_idx if not exists on ds_tweet("text") type fulltext;`

**Comment by waans11** [comment]
The documentation can be found at here:
https://ci.apache.org/projects/asterixdb/aql/fulltext.html

**Comment by waans11** [comment]
So, we need to remove jaccard > 0 part and replace contains to ftcontains.

**Comment by chenlica** [comment]
Great to see the full-text search in action :-)
