### ISSUE TITLE
Send deletion query from cloudberry to AsterixDB to finish deregistering process

### ISSUE THREAD

**Issue by haochen07** [ISG-ICS/cloudberry#305]
Now the DDL is almost finished! 
The cloudberry can receive register/deregister json request from front-end, and in registering process, cloudberry is able to keep that information in `metaData` and flush to database; in deregistering process, cloudberry can remove the dataset from `metaData` but not able to update the information to database because the deletion query is not defined inside cloudberry. Once it is done, the whole register/deregister process is finished from front to end.

**Comment by haochen07** [comment]
@luochen01 Could you enable a deletion query in cloudberry? I can handle all other logics concerning deregister process. Thanks

**Comment by luochen01** [comment]
What kind of delete query is required? Only delete one tuple/record, or delete the whole dataset?
It would be good to have a concrete use case/example here.

**Comment by haochen07** [comment]
In `DataStoreManager`, the `metaData` stores all the dataset infos and periodically flush them to database. What we need is when we remove a dataset info from `metaData`, we send a query to database and the removed dataset info will also be removed from dataset.

**Comment by JavierJia** [comment]
delete one record from the meta dataset.

**Comment by luochen01** [comment]
Then I would assume we can add a filter to the delete statement? Those records satisfying this filter would be deleted (to be consistent with most database systems).

**Comment by JavierJia** [comment]
correct!

**Comment by luochen01** [comment]
Now `DeleteRecord` query is available for SQLPPGenerator. You can go ahead with the deregister dataset feature.
