### ISSUE TITLE
TODO: Implement the Cache module

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#31]
Research on the design of the Cache module, should it be a mem-cache service or only work for each middleware itself?

**Comment by JavierJia** [comment]
Two options

1. [Akka distribute data](http://doc.akka.io/docs/akka/snapshot/scala/distributed-data.html)
2. [Spray-cache](http://spray.io/documentation/1.2.2/spray-caching/)

**Comment by JavierJia** [comment]
"Vignesh Sankar
Vidhya"

**Comment by chenlica** [comment]
Will do in the future.
