### ISSUE TITLE
Design the middleware cluster

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#32]
Need to research more about the details of how to arrange the ViewActors.

**Comment by JavierJia** [comment]
Akka cluster pub-sub is a good candidate to let only one leader to operate the update and let the rest of the subscribers listen to the changes.

**Comment by JavierJia** [comment]
By using the Actor model, it is very easy to horizontally scale. Leave it to the last step.

**Comment by chenlica** [comment]
Currently the middleware is light weight as most computation is done by the DB layer.  So the need of having a clustered middleware is low for now.
