### ISSUE TITLE
Cloudberry should supports static dataset

### ISSUE THREAD

**Issue by haochen07** [ISG-ICS/cloudberry#338]
Cloudberry now only supports dataset that has a `timeField`. For some of the datasets where information is rather static and mainly used for lookups, the way we handle them now is to append a fake `timeField` in the schema, which is not elegant and fails to return `Stats` information.
We need to distinguish `dynamic dataset` and `static dataset`, and different `Stats` respectively, and treat them in proper way.

**Comment by chenlica** [comment]
Per our discussion, please add our proposed plan to this issue for our records.

**Comment by haochen07** [comment]
- Add a field `type` to ddl, refer to `dynamic` dataset or `static` dataset.
- Dynamic datasets are required to assign a `timeField`, while in Static datasets it is optional. `timeField` in Static datasets will be treated no different as other dimensions.
- For static datasets:
  - In `QueryPlanner`, all queries will be executed directly to database, no views.
  - Static datasets will ignore `suggestViews` logic.
  - In `QuerySlicing`, do not slice.
- Design new trait `IStats`. Previous `Stats` will be `dynamicStats`. `StaticStats` will get rid of all `timeField` things and support `cardinality` for the moment.
- In `Register`, collect `IStats` and append it to `meta` table.

**Comment by haochen07** [comment]
@chenlica @JavierJia You can have a review on it.

**Comment by chenlica** [comment]
The plan LGTM.

**Comment by JavierJia** [comment]
👍
