### ISSUE TITLE
Multiple keywords should be sent as a collection of keywords, not a single keyword.

### ISSUE THREAD

**Issue by waans11** [ISG-ICS/cloudberry#347]
If a user enters "happy new year", then it should be tokenized properly.

Currently, Cloudberry uses the following that is not supported by AsterxDB.
ftcontains($o.text,{'happy new year'},{'mode':'all'})

The correct way is sending the following.
ftcontains($o.text,{'happy', 'new', 'year'},{'mode':'all'})

**Comment by luochen01** [comment]
Fixed.
