### ISSUE TITLE
Support SQL backend

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#372]
Currently Cloudberry supports AsterixDB as its backend using a translator to SQL++.  To make Cloudberry more general, we want to support other backends as well.  

In https://github.com/ISG-ICS/cloudberry/issues/287 we finished the step of supporting SparkSQL, and its core is really SQL.  In this issue, we want to fully support SQL on top of the previous PR.  Specifically:

Step 1: Support write operators using SQL;
Step 2: Setup a TwitterMap using MySQL as the backend.

**Comment by hh1680651** [comment]
![outline](https://user-images.githubusercontent.com/23527044/27887728-161f4418-6197-11e7-97df-931d4c332194.jpg)

**Comment by JavierJia** [comment]
Here are steps based on our discussion
* [ ] insert the data into the MySQL db. 
* [ ] summarize the differences between the SparkSQL with the MySQL queries. Depend on the number of differences, we will decide the design strategy.
