### ISSUE TITLE
FileFeedDriver needs to be adjusted (ADM/JSON and AQL/SQL++)

### ISSUE THREAD

**Issue by waans11** [ISG-ICS/cloudberry#417]
We currently use /aql (AQL) to fetch ADM instances like the following.

cat <<‘EOF’ | curl -XPOST --header “Accept:application/x-adm” --data-binary @- http://actinium.ics.uci.edu:19002/aql
use dataverse twitter;
for $t in dataset ds_tweet where ftcontains($t.text, [‘PikeCountyShooting’,‘DallasPoliceShooting’], {‘mode’:‘any’})
return $t
EOF

This will generate each ADM record per line as follows:
{"create_at":...}
{"create_at":...}
{"create_at":...}
{"create_at":...}

However, if we use /query/service (SQL++) like the following, it generated an array of ADM records. However, all string literal is encoded. 

curl -v -XPOST http://actinium.ics.uci.edu:19002/query/service -d “format=application/x-adm&statement=select value d from twitter.ds_tweet d where ftcontains(d.text, [‘keyword’], {‘mode’:‘any’})”

[ "{ \"create_at\":  ... ... } }\n", "{ \"create_at\": ... } }\n" ]

We need to work on FileFeedDriver to support this format.

**Comment by baiqiushi** [comment]
Low priority.

**Comment by chenlica** [comment]
Will close it.
