### ISSUE TITLE
Frontend crashed

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#42]
Here's a screenshot of a frontend bug.

![screen shot 2016-05-19 at 11 06 42 pm](https://cloud.githubusercontent.com/assets/12926365/15418782/8d630cbe-1e16-11e6-885f-2b9b0e9a37a6.png)

@JavierJia @JeremyLi28

**Comment by JavierJia** [comment]
It's known python server problem. We are all working on the new framework, so I'd like to switch to it ASAP.

**Comment by JavierJia** [comment]
One more thing for the new play framework, I'm working on getting the tweet id requests which is the only unaddressed issue. It will be soon...
