### ISSUE TITLE
Stopword filtering feature on the frontend (TwitterMap)

### ISSUE THREAD

**Issue by waans11** [ISG-ICS/cloudberry#434]
It would be nice to have a stopword filtering feature on the frontend.
This "stopword filtering feature" can work as follows:

1. A user types  one or more keywords and clicks "Submit".
2. When creating an actual query, we check these keywords and filters out stopwords. For example, "house of cards" will become "house cards". The final query will be generated based on the filtered keywords.
3. If no keywords are left after filtering "stopwords", the frontend alerts the user and clears the keywords in the search box.

**Comment by waans11** [comment]
English stopwords list:
https://www.ranks.nl/stopwords

**Comment by ChankiWu** [comment]
OK,I will work on that !

**Comment by waans11** [comment]
Merged. #479
