### ISSUE TITLE
Simplify frontend requests by moving them from TwitterMap web page to TwitterMap server

### ISSUE THREAD

**Issue by haochen07** [ISG-ICS/cloudberry#435]
This issue is continued to Issue #416 

As the TwitterMap server is on, we need to redesign the Json request sent from front-end to TwitterMap server so that the front-end only transmits necessary information instead of fully formatted cloudberry requests. This would beautify front-end Json format by making it more user-friendly, and TwitterMap server will take those requests and render them into corresponding cloudberry requests.
This draft below is one example of how we could define the front-end requests.

```
{
  click: {
    keyword: [],
    samples: [],
    normalization: true/false,
    ...
  } 
  drag: {
    map: {}
    timeline: {},
    ...
  }
  ...
}
```

**Comment by chenlica** [comment]
Will close.
