### ISSUE TITLE
Heatmap solution by image generation from middleware layer

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#437]
There are two options to generate a heatmap for geotagged tweets. 
(1) Middleware layer provides coordinates and the frontend renders the heatmap (i.e. Javascript on browsers).
(2) Middleware layer generate heatmap images directly and the frontend only shows the image.
This issue will focus on option (2).
For this researching topic, there are several open questions for exploration gradually.
a) As queries vary with different keywords, how to cache the results previously computed?
b) As new data is ingested into the system continuously, how to incrementally update the images?

**Comment by chenlica** [comment]
Will close.
