### ISSUE TITLE
Make a mockup design for the political ui design

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#44]
@JeremyLi28 You can do some research about what kind of information we want to show on the UI.

**Comment by JeremyLi28** [comment]
Some brainstorm for now:
+ Sentimental analysis (basically just counting the positive/negative words), similar to [this](https://www.csc.ncsu.edu/faculty/healey/tweet_viz/tweet_app/)
+ Some nice visualization to show the trends of candidates [here](http://react.brandwatch.com/uselection16/index.php?party=Democrats&utm_content=buffer408f4&utm_medium=social&utm_source=react-twitter&utm_campaign=owned+social)

**Comment by chenlica** [comment]
A good start! We have to care about the "usefulness" of the UI.  Plus our system should be much faster than theirs.

PS: It's interesting to have two "Chen Li"'s on the same project.
