### ISSUE TITLE
Error message in browser console, caused by loadGeoJsonFiles() in the map/controller.js

### ISSUE THREAD

**Issue by tejiaz** [ISG-ICS/cloudberry#457]
After set up two terminals to run a local demo, at the first time when use browser to open localhost window, there's an error message in the browser console says that: 
{
Error: An attempt was made to use an object that is not, or is no longer, usable query@http://localhost:9001/assets/javascripts/common/services.js:356:15 
loadGeoJsonFiles/<@http://localhost:9001/assets/javascripts/map/controllers.js:647:15 
m/h.success/<@http://localhost:9001/assets/lib/angularjs/angular.min.js:93:302 
e/<@http://localhost:9001/assets/lib/angularjs/angular.min.js:126:404 
$eval@http://localhost:9001/assets/lib/angularjs/angular.min.js:141:43 
$digest@http://localhost:9001/assets/lib/angularjs/angular.min.js:138:132 
$apply@http://localhost:9001/assets/lib/angularjs/angular.min.js:141:339 
g@http://localhost:9001/assets/lib/angularjs/angular.min.js:94:137 
t@http://localhost:9001/assets/lib/angularjs/angular.min.js:98:260 
fg/</u.onload@http://localhost:9001/assets/lib/angularjs/angular.min.js:99:297
}

Symptom description:  
This only exists when open the localhost page on the first time. After refresh the page, it will be gone.
According to @waans11 , this maybe related to @DeyuChen 's last change. 

Screenshot:
![image](https://user-images.githubusercontent.com/27831480/33862819-7ffcc750-de99-11e7-8920-3b9f0f9e2782.png)

**Comment by chenlica** [comment]
Format the error message nicely.  Add a screenshot of the problem.

**Comment by baiqiushi** [comment]
@tejiaz  Please check whether this happens again.

**Comment by chenlica** [comment]
Will close.
