### ISSUE TITLE
Handling multiple queries in TwitterMap

### ISSUE THREAD

**Issue by waans11** [ISG-ICS/cloudberry#460]
Currently, the TwitterMap front-end blindly receives a result from the Cloudberry and uses it. So, whenever multiple queries are issued (e.g., a user drags or zooms-in quickly), those results cannot be handled properly. To fix this issue, the following needs to be done.

- A query has a unique ID (e.g., UUID).
- Front-end sends this unique ID as a part of parameters to Cloudberry.
- Cloudberry returns this unique ID as a part of the result for this query.
- Before updating the result, front-end checks whether the ID returned from Cloudberry is the same to the current query's ID, and only for that case, update the result.

**Comment by JavierJia** [comment]
We can reuse or extend the design of the `wrap` request to add `id` field. (ctrl+F *wrap* in our document webpage: http://cloudberry.ics.uci.edu/documentation/.

**Comment by chenlica** [comment]
@JavierJia already setup the architecture to make such extensions easy.  Great job!

**Comment by baiqiushi** [comment]
#467
