### ISSUE TITLE
Create a downstream actor for each "category" query.

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#463]
**Problem:** 
    Currently, `berryClient` only creates two downstream actors, one actor for non-slicing queries and the other actor (named `stream`) for slicing queries.  The problem is it will not allow any frontend user to send two different `category`s of slicing queries simultaneously, because the single `stream` actor will drop any previous slicing queries once it receives a new slicing query.

**Solution:**
    Before this solution, issue #467 should be solved first, because this issue needs the `category` parameter as a prerequisite.
    Change the logic of creating slicing-query actor to creating one actor which will be named with the value of `category` parameter inside the query's `transform` keyword, therefore, for each different `category` query, there will be one actor solving it.

**Comment by chenlica** [comment]
Clarification: here a "key" means a "type" of query.

@baiqiushi Please also include the original issue number and do cross referencing between these two issues.

**Comment by baiqiushi** [comment]
@chenlica  Sorry, I don't know there's any related issue exists there.
