### ISSUE TITLE
Implement a generic group by function `GeoCell`

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#469]
**Problem:**
Currently, Cloudberry provides 3 group by functions in correspondence to AsterixDB `spatial_cell` function, which are `GeoCellTenth`, `GeoCellHundredth` and `GeoCellThousandth`.  To translate to SQL++ queries, `GeoCellTenth` will look like this:
```group by get_points(spatial_cell(t.`coordinate`, create_point(0.0,0.0), 0.1, 0.1))[0] as `cell` group as g``` 
_NOTE:_ scale 0.1 means `Tenth`, likely, `Hundredth` will be 0.01 and `Thousandth` be 0.001

**Solution:**
Replace the current implementation of  3 static scale choices with a generic `GeoCell` function and `scale` should be parameter of the function.

**Comment by chenlica** [comment]
@baiqiushi status?

**Comment by baiqiushi** [comment]
Low priority.
