### ISSUE TITLE
Wrap conf parameters of Twittermap application into objects

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#480]
**Problem**
Twittermap application uses `application.conf` file to store configuration parameters. When the `TwitterMapApplication.scala` starts up, it loads the parameters into web html files and javascript objects. Currently, these parameters are transferred in a way all aligned together between files and codes. Apparently, it's not a good practice.

**Solution**
Whether it's possible is not quite clear yet. When `TwitterMapApplication.scala` initialize the `index.scala.html` and `main.scala.html` files, wrap the parameters into several objects based on their purpose and usage.

**Related technology**
 - Scala
 - Play Framework

**Comment by chenlica** [comment]
@ChankiWu Good luck to your first backend task!
