### ISSUE TITLE
Tweet number doesn't change; the ingestion process cannot be reached

### ISSUE THREAD

**Issue by waans11** [ISG-ICS/cloudberry#508]
Symptom:

#1. The Twittermap (cloudberry.ics.uci.edu/apps/twittermap/) did not show incremental numbers for incoming tweets. 

#2. Checking DBURL/admin/active did not yield any update on the tweet count, either.

#3. The machine (a NUC machine) that hosts the ingestion process cannot be reached using ssh, either. Finally, using a keyboard, mouse, and monitor, Ian and I were able to connect to the machine directly. The machine was not in a panic. Ian was able to login to the machine. The command "top" showed the ingestion process was running with high CPU utilization (90%). When Ian checked the system log ("/var/log/messages"), Ian found that the network driver generated an exception and was not able to get an IP address from the server afterward. We stopped the network interface and started it again to get the IP address from the DHCP server. Ian applied patch sets using "sudo yum update" and restarted the machine. If this error happens again, we may need to search the error messages and find a specific resolution for this.

**Comment by chenlica** [comment]
@waans11 status? close it?

**Comment by waans11** [comment]
Ah, yes, this was due to the network driver issue of CentOS. Ian fixed it.
