### ISSUE TITLE
Vulnerabilities in dependencies defined in doc/Gemfile.lock

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#509]
**Symptom**

![image](https://user-images.githubusercontent.com/8113414/40098943-bf3d4a3e-5892-11e8-9df5-479fb3cdbb2d.png)

![image](https://user-images.githubusercontent.com/8113414/40098868-772c3930-5892-11e8-8772-9ad67c9543bc.png)

**Comment by chenlica** [comment]
@baiqiushi @waans11 : any idea about how to get rid of this warning?

**Comment by baiqiushi** [comment]
https://help.github.com/articles/viewing-and-updating-vulnerable-dependencies-in-your-repository/

**Comment by baiqiushi** [comment]
#538
