### ISSUE TITLE
Proposing the way to show sentiment score for tweets

### ISSUE THREAD

**Issue by taoenkh** [ISG-ICS/cloudberry#514]
Previously, I have been working on how to show sentiment values for the tweets. I have come up with two ways. The first one is to change each state's border a color that each color represents the average sentiment score for that state. The second solution is for the pin map, which is change to color of the tweets on the pin map. Currently, I am working on shifting the border for each state/county that can make the sentiment score for each state/county more clear.

**Comment by baiqiushi** [comment]
Deprecated.
