### ISSUE TITLE
Refactoring front end control 

### ISSUE THREAD

**Issue by AC-Unicorn** [ISG-ICS/cloudberry#515]
- [x] introduce multilayer-manager

- [ ] introduce heatmap service and multilayer service

- [x] modify common/service activate multilayer-manger with heatmap

- [ ] introduce pinmap service

- [ ] introduce polygon layer service

- [x] introduce countmap service

**Comment by AC-Unicorn** [comment]
after the discussion with professor Li, teawoo, qiushi bai, and teyu. We have consent on the new design of front end control. This week I have finished documenting the detail of front end control and start implementing it.

**Comment by chenlica** [comment]
Can you add a URL of the design doc?  

BTW, I like your github account name, Chairman Kim :-)

**Comment by AC-Unicorn** [comment]
https://docs.google.com/document/d/1Q88mQxf1vaeiTdjFbXTLTr4Ymq-OCimb6etCoiF_7Ls/edit?usp=sharing

**Comment by baiqiushi** [comment]
Low priority.
