### ISSUE TITLE
WebGL-based Frontend Library

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#516]
**Outline**
 - WebGL is a cross-platform, royalty-free API used to create 3D graphics in a Web browser.
    https://www.khronos.org/webgl/wiki/Getting_Started
 - Through WebGL, we can render a large number of points in the browser quickly and compactly.

**Demo**
http://vps2.shuangz.com/tmp/pinmap2.html

**Plan**
 - May 25, 2018. Shuang's team will develop a Leaflet.js Plugin first, then will be integrated to Twittermap to replace the current Plugin [leaflet-maskcanvas](https://github.com/domoritz/leaflet-maskcanvas).

**Reference**
 - Currently, using `leaflet-maskcanvas` to render points for PinMap:
```
Count ( points ) = 120,000,  total memory profile of Chrome = 510MB,  Scan array time = 1 ms
Count ( points ) = 480,  total memory profile of Chrome = 290MB, Scan array time = 0 ms
```
Observation: rendering time is not an issue, but the memory is a concern for a large number of points.

**Comment by chenlica** [comment]
@baiqiushi close it by including the PR.

**Comment by baiqiushi** [comment]
#610
