### ISSUE TITLE
Implementing embedded database on cloudberry storing the meta-data

### ISSUE THREAD

**Issue by taoenkh** [ISG-ICS/cloudberry#523]
- Currently, made a comparison between Derby and SQLite. 
- According to "db-engines.com",  SQLite has a higher ranking in the DB-Engines, its implementation language is C, and it supports many programming languages. 
- I think that SQLite is a better embedded-database comparing to other embedded-database,  and can be a good choice to store our cloudberry's meta-data.

**Comment by baiqiushi** [comment]
Currently, we will stick to the design that use target backend database as metadata store as well.
