### ISSUE TITLE
Profiling Results - Potential Performance Improvement

### ISSUE THREAD

**Issue by Yishanmys** [ISG-ICS/cloudberry#529]
- Based on the profiling report (link attached below), I have these conclusions:
https://docs.google.com/document/d/1xS96-MEcQWLfadsrQG2G9ak0WofZ27f-9OX6n4GxbPk/edit

- Loading page part is good enough. The process is reasonable with the css and javascript files loaded first, and the state.json loaded second, and draw the state border right after loading the state.json, finally load the county.json, which is not affecting user experience.

- Since the query was sent through websocket, I cannot tell whether the examples was loaded synchronized with query result. So I focused on testing the time each query took.

- Results below are done with 4-time slowdown and incognito mode of Chrome:
![image](https://user-images.githubusercontent.com/33766363/41926807-3daab264-7925-11e8-86ed-f0555a32a484.png)
![image](https://user-images.githubusercontent.com/33766363/41926784-30595520-7925-11e8-9828-c7586bb531b5.png)

- 
![image](https://user-images.githubusercontent.com/33766363/41926818-45490976-7925-11e8-991c-e9ede6770133.png)
![image](https://user-images.githubusercontent.com/33766363/41926826-48eb0232-7925-11e8-8ef9-55a0857aa5ca.png)

- Results below are done without throttling
![image](https://user-images.githubusercontent.com/33766363/41927337-cc74599a-7926-11e8-9fdc-c6014f8e0ced.png)
![image](https://user-images.githubusercontent.com/33766363/41927341-d0701e76-7926-11e8-8b62-03ad05b09b71.png)

![image](https://user-images.githubusercontent.com/33766363/41927350-d88b4f0e-7926-11e8-8d1e-99dbe03ae283.png)
![image](https://user-images.githubusercontent.com/33766363/41927354-db1f4ef0-7926-11e8-9327-c32c000c645d.png)

- There can be a potential performance improvement when search the same keyword at the same area, time for the second searching is almost the same as the initial searching time.

- Potential improvement may include add a case when the county or state id in the cache is exactly the same, then there won't be a query sent to cloudberry.

**Comment by chenlica** [comment]
@Yishanmys It will be good to add all the results in this issue, including those images, without relying on an external URL.  Can you do that?  Thanks.

**Comment by chenlica** [comment]
This work is done.  I am going to close it.
