### ISSUE TITLE
Zoom in to city level details

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#53]
The frontend can ask the shapes as needed, not like the state and county shapes which were loaded at the beginning.

**Comment by JavierJia** [comment]
@zonghengma

**Comment by JavierJia** [comment]
@zonghenma, you can take a look at the js code inside  `neo/public/javascripts/map/controllers.js`

**Comment by zonghengma** [comment]
If just load the entire city data, the webpage gets stuck for around 10 seconds on my machine when it is first loaded. It also gets stuck for 5 seconds or so when the map is zoomed into city level.

**Comment by JavierJia** [comment]
sounds cool. could send a PR (pull request) about the change? we don't need to merge, but we can have a check about the code.

**Comment by zonghengma** [comment]
Great. I'll do it as soon as I get home.

**Comment by JavierJia** [comment]
No rush 😄

**Comment by chenlica** [comment]
Cool.  It verified the conjecture that loading too much city data to the browser will slow down the response.  For our record, what's the size of the city data?

After @JavierJia checks your code, please start working on the idea we discussed last time: the frontend loads data from the middleware those cities in a certain region.  We also need to implement a function in the middleware to find cities in a region by scanning all the cities.

**Comment by zonghengma** [comment]
Updates: I have attempted to load the entire city data in the beginning. However, this makes the webpage to get stuck completely for about 10 sec in the beginning as well as when zoom into city levels. Once in city level, the map becomes very unresponsive. We can conclude that this is not an acceptable way. I am currently trying to only load the city data inside within the map currently being shown in the window. This contains modifications in the middleware as well. I'll post new updates here as soon as I have new findings.

**Comment by zonghengma** [comment]
Updates:
The middleware can now calculates the mid-points of the cities on first launch. 
Front-end can send a get request whenever the map is dragged in city level.
Todo:
Store the mid-points someway in order and return to front-end as need.

@JavierJia Do we need to change the calculation of mid-points of states and counties from the front-end to middleware? It is kind of messy if we calculate some mid-points in the middleware and some in the front-end.

**Comment by chenlica** [comment]
Cool!  Looking forward to the demo with the city-level details!

**Comment by JavierJia** [comment]
@zonghengma Processing by the front-end is an ideal case which can save a lot msg passing to middleware. Use middleware is a fallback because the city is too big to process in front-end.

**Comment by JavierJia** [comment]
@zonghengma can upload a PR for review?

**Comment by zonghengma** [comment]
@JavierJia I created a PR for what I have now. I'll update it soon
