### ISSUE TITLE
Loading strategy of Inverted Index in PostgreSQL

### ISSUE THREAD

**Issue by liming-thu** [ISG-ICS/cloudberry#532]
In postgreSQL, for a specific range of keyword frequency, the execution time of different keywords varies greatly, e.g. in a data-set of 10M, 2 keywords A and B are of the frequency range of 80K~90K, their execution time is 2s and 20s respectively. No matter how to change the order of queries, or try to flush the buffers, the execution time is still the same. After some investigations, I found this problem is related to the loading strategy of inverted index.
The DB engine uses a buffer called 'work_mem' to cache the Inverted Index. The type of the Inverted Index in postgreSQL is Bitmap index. In the inverted index, each keyword has a list of item which contains the record ID and page ID that contains the keyword, when the 'work_mem' is not large enough, then when loading the inverted index, instead of loading the full list of recordID, the system only loading the pageID, that is in the Bitmap of 'work_mem', the list of the keyword only stores the pageID which contains the keyword, so when querying this keyword, the DB engine has to fetch all the pages in the list, and do a seq-scan of all the records to get the correct ones.
In the explanation of the execution plan, if one page is fetched and filtered by RecordID and PageID, then it is called ‘exact’ page, otherwise, if it is fetched only by PageID and need to be seq-scanned, then it is called 'lossy' page.
![exact and lossy](https://user-images.githubusercontent.com/12154187/42066953-8b760f5a-7af8-11e8-80b5-296f23337475.jpg)
Reference:
https://paquier.xyz/postgresql-2/postgres-9-4-feature-highlight-lossyexact-pages-for-bitmap-heap-scan/
https://www.postgresql.org/message-id/005401ced6f1%24e2005ca0%24a60115e0%24%40lab.ntt.co.jp
https://dba.stackexchange.com/questions/126746/what-does-heap-block-in-bitmap-heap-scan-mean

**Comment by chenlica** [comment]
Thanks.  We may need to revise it after a discussion with @waans11 .
