### ISSUE TITLE
Oracle Adapter

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#535]
#### Overview ####
Develop another adapter for Cloudberry to support Oracle as a backend database.

#### Progress ####
@weifeng has initialized the codebase for this work. And the made the `register` query work.

#### Known Issues ####
 - Make sure whether the `typeName` under `schema` in registering dataset message to Cloudberry
is necessary or not, if necessary, it's unique concept in AsterixDB, we need to use some arbitrary value for that, say `table name`
 - What if primary key is a composite key
 - Be careful that in Oracle the table names or field names can not be wrapped with quotation marks
 - `Date` type field needs to be in syntax like this: `to_date('2018-06-01', 'yyyy-mm-dd')`
 - Oracle does not support some syntax keywords such as `replace into`, `exist`, `limit`, etc
 - Make sure how the mechanism of "dot"(`.`) in Oracle works, and replace the `database` concept in AsterixDB or MySQL with `tablespace` concept in Oracle
 - Be careful that in Oracle, `VARCHAR` field does not have operator `=`
 - Be careful that in Oracle, all field names returned are in upper case by default
 - More thoughts might need to be put into for `limit` keyword and new data types in Oracle

**Comment by chenlica** [comment]
@waans11 , @baiqiushi : please use English :-)  Also please add Tao to github if we haven't done so.

**Comment by chenlica** [comment]
@baiqiushi @taoenkh : should we close it since we have another related issue?

**Comment by baiqiushi** [comment]
#617
