### ISSUE TITLE
Cloudberry backend DB generalization

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#536]
## Overview ##
When we develop a new DB adapter for Oracle Database #535, we find several places in Cloudberry made some assumptions that are not general enough for other Backend database adapters.

#### Field name case sensitivity ####
In file [DataStoreManager.scala](https://github.com/ISG-ICS/cloudberry/blob/master/cloudberry/zion/src/main/scala/edu/uci/ics/cloudberry/zion/actor/DataStoreManager.scala):
line 294 - 296
```
minTime <- conn.postQuery(parser.generate(minTimeQuery, Map(dataset -> schema))).map(r => (r \\ "min").head.as[String])
maxTime <- conn.postQuery(parser.generate(maxTimeQuery, Map(dataset -> schema))).map(r => (r \\ "max").head.as[String])
cardinality <- conn.postQuery(parser.generate(cardinalityQuery, Map(dataset -> schema))).map(r => (r \\ "count").head.as[Long])
```
Here the regex expression uses lower case which will cause problem for Oracle because Oracle returns query results with field names all being upper case by default.

#### TimeField format ####
In file [AbstractSchema.scala](https://github.com/ISG-ICS/cloudberry/blob/master/cloudberry/zion/src/main/scala/edu/uci/ics/cloudberry/zion/model/schema/AbstractSchema.scala):
line 105 - 108
```
object TimeField {
  val TimeFormat = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
  val TimeFormatForSQL = DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss.SSS")
}
```
Here the `TimeFormatForSQL` is assuming that all SQL databases support this `TIMESTAMP` type format, but actually Oracle uses the format like this: `DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss.S")`

**Comment by chenlica** [comment]
@baiqiushi status?

**Comment by baiqiushi** [comment]
Not needed anymore.
