### ISSUE TITLE
Visualizing correlation of two keywords on Twittermap

### ISSUE THREAD

**Issue by yangguah** [ISG-ICS/cloudberry#548]
### First try--using correlation formula in terms of statistics
The work I was given is to show the relation of two keywords at a state level, county level and city level in the twittermap. By using the correlation formula, I transferred the relation of two keywords into a number in the range of [-1,1]. 
To be specific, the correlation formula is
![qq20180717-203131](https://user-images.githubusercontent.com/18154647/42857854-92f99082-8a00-11e8-8bd1-4674ec584d44.png)
![qq20180717-203918](https://user-images.githubusercontent.com/18154647/42858047-859a787e-8a01-11e8-99a6-6a382a633aef.png)
For example, in every state, I divide it into 8x8 girds. For each gird I could get the count of tweets where the first keyword appears and the count of tweets where the second keyword appears and then I applied the correlation formula.

However, this method did not make sense because it only showed the
correlation of the distribution of the population in each region but not the correlation between the two keywords. The correlation we defined here actually is the possibility of two keywords being talked both at the same tweet.

**Comment by yangguah** [comment]
### Spring quarter's work
### Second try--using Jaccard function
Next, I changed to define the meaning of the relation of two keywords A and B as the possibility of
when people refer A in a tweet they will also refer B in the same tweet and vice versa. Next I
changed to define the meaning of the relation of two keywords A and B as the possibility of
when people refer A in a tweet they will also refer B in the same tweet and vice versa. And then I
applied the Jaccard index as 
![qq20180717-211044](https://user-images.githubusercontent.com/18154647/42858910-f124917a-8a05-11e8-8253-e15274291b49.png)
![qq20180717-211059](https://user-images.githubusercontent.com/18154647/42858914-f6bfbdc6-8a05-11e8-9dd6-3bec0dc48f83.png)

**Comment by yangguah** [comment]
## Summer's work
### using Jaccard function and treat each user's all tweets in one place as one document.
Since each tweet has very few words, a user may say "Kobe is great!" in a tweet and then say "I love Bryant"  in another tweet. Our intuition actually wants to regard these two tweets as one tweet because in this way " 'Kobe' intersects 'Bryant' " will be 1. If these tweets are seperate, the result " 'Kobe' intersects 'Bryant'  " will be 0, but we regard "Kobe" and "Bryant" are in one tweet.
Beside, Qiushi helped check that backup server had 3 million distinct users among 50 million tweets, which means that each user has 16 tweets on average. Good news is that there is no unknown user in the datebase.
![qq20180717-215232](https://user-images.githubusercontent.com/18154647/42860532-e5b62b5e-8a0b-11e8-939f-c68a866a6c8a.png)

**Comment by yangguah** [comment]
### Summer's work
### How I implemented the task
1. Create six different queries and each of them is sent to the Cloudberry based on the keyword and group tweets by state_id and user_id in state level or group them by county_id and user_id in county_level or group them by city_id and user_id in city level.
For example, a query sent to the cloudberry based on the keyword "Los" and grouped by state_id and user_id would be like this:

**Comment by yangguah** [comment]
### Summer's work
### How I implemented the task
2. Process the data.
After getting the results from Cloudberry, I managed to Load the results into the state level and county level. For example, based the first keyword "Los", I store the number of users whose tweets containg "Los" in every state into a variable named "state_counts"

**Comment by yangguah** [comment]
### Summer's work
### How I implemented the task
4. Load a larger dataset and measure the query time and frontend calculation time
I loaded the dataset that contains all the tweets from January 24th, 2017 to January 3rd. The number of tweets is 4289787.
![qq20180708-215542](https://user-images.githubusercontent.com/18154647/43048512-b0379586-8d9d-11e8-894a-9214f537fd5b.png)
Then for each query sent to the cloudberry, I checked the time that I get the results from cloudberry.
For example:
![qq20180722-110358](https://user-images.githubusercontent.com/18154647/43048600-fa0bc38e-8d9e-11e8-86de-fbd308c19edc.png)
"finished_count=1" means that I have sent the first query to cloudberry and got the results from the cloudberry. "t2" is the time when I start sending the first query to cloudberry. "T" is the time when I have got the results from cloudberry based on the first query.
For keywords "los" and "angeles", the time each query takes is:
![qq20180722-111154](https://user-images.githubusercontent.com/18154647/43048659-216a28a2-8da0-11e8-9d70-c735b250d1af.png)
Six queries take around 23 seconds and each takes around 3.8 seconds, which is expensive.
While, right now my focus is on checking the sense of Jaccord function instead of the query time.
Next I would try different combinations of keywords and analyze whether Jaccard function is proper to our correlation map.

**Comment by yangguah** [comment]
### Try different combinations of keywords
| Key1  |Key2   |        || Description  | Analysis  |
| ------------ | ------------ | ------------ | ------------ |------------ |
| New  | York  |   | | | |
|   |   |   |   | |   |
|   |   |   |   | |   |

**Comment by yangguah** [comment]
###summary
After connecting to our back-server, I still cannot come up with a pair of keywords that inspire people. The keywords are either related to each other or not related to each other and there is nothing more meaningful information. The sense of Jaccard function can be converted such a question that "If two keywords are related, can we get a deeper meaning from this?"  Unfortunately, the Jaccard function does not make sense if we do not solve this question.

**Comment by chenlica** [comment]
I am going to close this issue.  The conclusion is: we haven't found a good meaning or use case of correlation map.

@yangguah : Thank you.
