### ISSUE TITLE
Oracle Adapter

### ISSUE THREAD

**Issue by taoenkh** [ISG-ICS/cloudberry#552]
# Oracle Adapter #
#### Overview ####
Develop another adapter for Cloudberry to support Oracle as a backend database.

## Tutorial to add ojdbc into cloudberry's dependencies
To add OJDBC in cloudberry's dependencies, the Apache Maven should be installed in advance. 

### Installing Apache Maven
It is available to download Apache Maven from the following url https://maven.apache.org/download.cgi, and make sure JDK is install and JAVA_HOME is added to the enviroment variable. 

Choosing one of the following links and unzip it (works same for every operating system).
Recommended to download the *Binary zip archive*.
![image](https://user-images.githubusercontent.com/17862052/43032307-8dfffdcc-8c68-11e8-91b0-bee198820f31.png)

After downloading the zip file, unzip it with any tools and set the M2 enviroment variable.

#### Setting the environmental variable of M2_HOME for Windows

Assume you unzip to this folder – C:\Program Files\Apache\maven
Add both M2_HOME and MAVEN_HOME variables in the Windows environment, and point it to your Maven folder.
![image](https://user-images.githubusercontent.com/17862052/43032391-7c01f22c-8c6a-11e8-96ea-2bd214830443.png)

Update PATH variable, append Maven bin folder – %M2_HOME%\bin.

![image](https://user-images.githubusercontent.com/17862052/43032398-c98b642e-8c6a-11e8-84ba-3bd912e26f1f.png)

Running the following command on cmd will add the ojdbc to Maven's dependencies.
`mvn install:install-file  -Dfile={Enter the aboslute path of OJDBC.jar }  -DgroupId=com.oracle  -DartifactId=ojdbc7  -
Dversion=12.1.0.2  -Dpackaging=jar  -DgeneratePom=true`

### Changes to make to add maven dependencies on Cloudberry
In `cloudberry/project/dependencies.scala` module add the OJDBC jar in zion dependencies field.
![image](https://user-images.githubusercontent.com/17862052/43033138-5a277f14-8c79-11e8-8b1c-a4df890d33ac.png)

In `cloudberry/project/commons.scala` module add Resolver.mavenLocal to add Maven dependencies to cloudberry.
![image](https://user-images.githubusercontent.com/17862052/43033181-84215ac8-8c7a-11e8-816a-6419532383f5.png)
After making these changes Cloudberry will be able to talk to Oracle database.
To set up Oracle's url please make modifications in `application.conf`

## Tutorial to install Curl on Windows
*Using Restful Client on Windows will encounter problem when recieving a response from clouberry after a `berry` command is sent.*
Installing curl will be also required on Windows.

### Step 1 Downloading the Curl
Visiting the Curl's website to choose your appropriate version coresponding to your OS. 

![image](https://user-images.githubusercontent.com/17862052/43229727-a760eee2-901a-11e8-9070-8979e33e69a7.png)

Win64 Generic is the most common one for windows users.
After clicking the link of Stefan Kantak, a tutorial and licenses of curl will be shown.
Then scroll down to installation to download the curl.
![image](https://user-images.githubusercontent.com/17862052/43230147-1b56fc50-901c-11e8-8932-5c65227d497c.png)

### Step 2 Setting the Environment variable of Curl
After extracting the `.cab` file, visiting `\curl-7.61.0\AMD64` will show the `CURL.EXE`.
To use curl we can simple `cd` to the directory and use the curl as the ways used in other Operating System. 
In order to use Curl everywhere, setting of Environment variable is required.
![image](https://user-images.githubusercontent.com/17862052/43232357-481e958c-9025-11e8-9f6d-ecb9ec648125.png)
Update PATH variable, append the directory where curl is extracted

 

## Progress ##
@weifeng has initialized the codebase for this work. And the made the `register` query work.

- Fixed the supporting of "berry.meta" by adding double quoations. 

- Found the both PostgreSQL and Mysql used "berry.meta" as a prefix, "berry." rather than a Database in MySQL/Dataverse in AsterixDB/Tablespace in Oracle. Currently, following the logic of MySQL and PostgreSQL.

![image](https://user-images.githubusercontent.com/17862052/43065136-bb280944-8e15-11e8-9d76-0c27f27b4d24.png)

**Previous work on `register` query might have potential errors, since sending a json with Timefield via Rest Client can cause an exception from cloudberry.**

**Currently, choose the way to fix if exist syntax that is not supported by *Oracle*, and other syntaxes that are not supported by *Oracle*.**

### Possible ways to solve if exists ###
- Use Try{} catch{}   (Works ok right now, **Might have potential problems**)
![image](https://user-images.githubusercontent.com/17862052/43064612-464cedac-8e14-11e8-8968-0dbe43db56aa.png)

- **Use procedure in Oracle (query works on SQL Developer, having problem on Cloudberry )**

![image](https://user-images.githubusercontent.com/17862052/43064786-ca74271c-8e14-11e8-941e-3a4e4644df19.png)
Changed data type of time field to TimeStamp, since date in Oracle does not include the exact time.

    //sample output
    // contains(name,'test',1)>0 equivalent to match(name) against ('+test' in boolean mode);
    // contains(name,'foo and bar',1)>0   equivalent to match(name) against ('+foo +bar' in boolean mode);
    // contains(name,'foo and bar and test',1 ) > 0   equivalent to match(name) against ('+foo + bar +test' in boolean mode);

### Latest Update
- Completed register
- Successfully ran a simple query using Oracle adapter

**Query send via Curl**
![image](https://user-images.githubusercontent.com/17862052/43167881-27943658-8f50-11e8-82e4-543fd00d0735.png)

**Query in SQL** 

`select t."NAME" as "NAME"
from "MYSQLDEMO" t
where t."NAME"='Tao'
limit 60000000;`

**Result from cloudberry** 
![image](https://user-images.githubusercontent.com/17862052/43168054-ad76849c-8f50-11e8-905b-fca36656651c.png)

**Table in Oracle Database**

![image](https://user-images.githubusercontent.com/17862052/43168088-cf3c63f8-8f50-11e8-99ac-de58238c35d7.png)

Currently, the simplest query works fine, but sending a create view might cause problems; comparison between dates still raises an exception. Since in MySQL we can directly compare strings in 'yyyy-mm-dd hh:mm:ss' format, in Oracle we must use to_date() to convert the string.

Example : `select * from qz_test where qz_test.startdate > '2016-01-01';` works on MySQL but not on Oracle.

**Overrode `parseDrop`**
Since Oracle does not support `if exist`, we are required to write `PL/SQL` to determine if a table is already created. 
![image](https://user-images.githubusercontent.com/17862052/43378608-ce656396-937c-11e8-81a7-61b517c892af.png)
**Overrode `ParseTimeRelation`**
This function will be called when sending a berry query to update the metadata.
Comparison between time fields will be required, since `lastReadTime` of `berry.meta`'s stats will be updated.
![image](https://user-images.githubusercontent.com/17862052/43380524-481c2e64-9386-11e8-94e3-5e5175da3baa.png)
**Change the connection of OJDBC**
![image](https://user-images.githubusercontent.com/17862052/43487104-69e0ca2e-94ca-11e8-8292-ad103a29d813.png)
Previously, the connection to Oracle was `Specifying a Databse URL, User Name, and Password`, which needs to specify `url`, `username`, and `password` seperately as three parameters.
![image](https://user-images.githubusercontent.com/17862052/43487209-cdb51078-94ca-11e8-8d95-42d98c807d7f.png)
To match the connection with `MySQL`, and `PostgreSQL`, I modified the connection to `Specifying a Databse URL That Includes User Name and Password`. 
![image](https://user-images.githubusercontent.com/17862052/43487288-107f58be-94cb-11e8-80c7-347c53a85f6f.png)
Putting both `username` and `password` on the `url`.
![image](https://user-images.githubusercontent.com/17862052/43487335-2f8a88a0-94cb-11e8-94e0-91954944b77a.png)
![image](https://user-images.githubusercontent.com/17862052/43487363-40bfdf3a-94cb-11e8-8228-e9367927c810.png)
**Overrode `parseSelect`**
This is the function that generates `limit`, which is not supported by `Oracle`.
In `Oracle 12C` `fetch first n rows` is the syntax that is almost same as `limit` keyword in `MySQL`.
![image](https://user-images.githubusercontent.com/17862052/43487519-c21dcbf0-94cb-11e8-9326-70f8661987c8.png)
**Overrode `parseGroupby`**
![image](https://user-images.githubusercontent.com/17862052/44234958-d48eed80-a15c-11e8-866d-9a42fc26923a.png)
In both `MySQL` and `PosgreSQL`, select statement executes before where statement, but `Oracle` works in a inverse way. If we say select `"geotag" as "state" where "text" = 'hurricane' group by "state";` we will receive a syntax error since during the executing of group by "geotag" was not renamed as "state" yet.
**Overrode `parseGroupByFunc`**
In cloudberr, the group by field has a attribute name "unit", which will extract a certain field of the timestamp. In `MySQL`, simly using date([DATE STRING]) or month([DATE STRING]) will be adequate. However, similar to `PostgreSQL`, `Oracle` also uses `extract()` function to get any time fields beside `Date`. To get date of a certain time field `to_char(cast([DATE] as date),'yyyy-mm-dd')`, and to extract other fields using extract(month from [DATE]) will be fine.
![image](https://user-images.githubusercontent.com/17862052/44235510-a4484e80-a15e-11e8-98bb-33ea29eeb0d5.png)
![image](https://user-images.githubusercontent.com/17862052/44235609-fdb07d80-a15e-11e8-96dd-7a86db35f642.png)
![image](https://user-images.githubusercontent.com/17862052/44235648-1456d480-a15f-11e8-8111-d7c6582ac9f8.png)

 

#### Functions need to be overrode (ALL Completed)
- `parseTimeRelation`
- `parseTextRelation`
- `parseDrop`
- `parseCreate`
- `parseSelect`
These function must be overrode due to the issues below, there might be possible issue not noticed yet.

## Issue(Solved)
`replace into `mysqldemo` (select * from `mysqldemo1`);` `MySQL` supports this syntax, not sure if oracle also supports

`merge into mysqldemo d using(
select * from mysqldemo1) b
on (d."ID" = b."ID" )
when not matched then
insert (d."ID",d."NAME",d."ADDRESS",d."CITY",d."COUNT",d."THEDATE")
values (b."ID",b."NAME",b."ADDRESS",b."CITY",b."COUNT",b."THEDATE");`
Found a possible solution.
### Update August 5th
- Completed the script to insert 46000 data to `MySQL`.
Rewrote the script since the previous one was in `PHP` and there were some errors that I was not sure how to solve.
- Inserted 46000 `tweets` to `MySQL`
![image](https://user-images.githubusercontent.com/17862052/43690822-e098c712-98c5-11e8-9e77-f9ab217fb7f5.png)
## Issue (using older version front-end solved the problem)
After I inserted all 4 `datasets` of `twitterMap` the `MySQL` back-end still has some issues.
I found that the `twitterMap` has different logics on different back-end database. Since `twitterMap` is very different from previous version, it is unable to run on our current version.
Then I downloaded the previous version of  `twitterMap`, and the `MySQL` backend works fine.
## Current Issue (Solved)
select t.`geo_tag.stateID` as `state`,count(*) as `count`
from `twitter_ds_tweet` t
where t.`create_at` >= '2018-08-11 12:32:41' and t.`create_at` < '2018-08-13 12:32:41' and t.`geo_tag.stateID` in ( 37,51,24,11,10,34,42,9,44,48,35,4,40,6,20,32,8,49,12,22,28,1,13,45,5,47,21,29,54,17,18,39,19,55,26,27,31,56,41,46,16,30,53,38,25,36,50,33,23,2 ) and match(t.`text`) against ('+zika' in boolean mode)
group by `state`; In `MySQL` the query works fine.
However, in `Oracle` we cannot group by "state"; we can only group by t."geo_tag.stateID".

#### Known Issues To fix ####

- [x]  Make sure whether the `typeName` under `schema` in registering dataset message to Cloudberry
is necessary or not, if necessary, it's a unique concept in AsterixDB, we need to use some arbitrary value for that, say `table name` 
- [x]  What if a primary key is a composite key (Tested on `SQL Developer` Oracle supports `composite key`)
 - [x] Be careful that in Oracle the table names or field names cannot be wrapped with quotation marks (Oracle 's table name uses double quotation marks, not a issue for now.)
 - [x] `Date` type field needs to be in syntax like this: `to_date('2018-06-01', 'yyyy-mm-dd')`
 - [x] Oracle does not support some syntax keywords such as `replace into`, `exist`, `limit`, etc (used merge into instead of replace into)
 - [x] Make sure how the mechanism of "dot"(`.`) in Oracle works, and replace the `database` concept in AsterixDB or MySQL with `tablespace` concept in Oracle
 -  [x] Be careful that in Oracle, `VARCHAR` field does not have operator `=`
 -  [x] Be careful that in Oracle, all field names returned are in upper case by default (**This can be fixed by adding double quotes**)
 - [x] More thoughts might need to be put into for `limit` keyword and new data types in Oracle.

### Monday July 23
- [x] Find the proper way to Check Oracle log including error logs. (Still using the previous way to check log, but found why the command was not working)
- [x] Test PLSQL query on a simple java program.
- [x] Try simple register and berry query of Mysql on a Mac or Linux machine  to make sure how cloudberry behaves. (Had problem on restclients, Mysql adapter works perfectly, using curl on windows solves the problem ) 
- [x] Create `berry.meta` table and other Oracle data in a `tablespace` other than `SYSTEM`.
### Tuesday July 24
- [x] Figure out that if `limit` keyword is a problem for Oracle (Eliminated the key work limit by professor Shan since the numbers were very large). TO DO use rownow in the future.
- [x] Change `insert into` to `merge into` (to use as `replace into` in `MySQL`).
### Wednesday, July 25
- [x] Write a tutorial about curl on windows, since restclient behaves incorrectly when receiving a response from Cloudberry.
- [x] Attempt to start debug the problems on Berry request. 
### July 27- 30
- [x] Try to solve the problem of details when sending a berryquery (solved some problem)
### Until August 2nd 
- [x] Try to complete all the functions required to send a berry query (Still working on `parseCreate` other might work fine)
- [x] Change the way Oracle is connected, currently the username and password is declared in a format different from other databases. 
### Monday August 6th
- [x] Try to ingest the data of `twitterMap` to `MySQL`
### Thursday August 9th 
- [x] Ingest the data of `twitterMap` to `Oracle`.
## Lastest Progress
OracleAdapter is almost done, the `twittermap` can run properly without problems with `Oracle` as the backend database.
# Summary
### Major differences from `MySQL` adapter
Changes | Explanation
------------ | -------------
Convert `if exists` to `pl/sql` | `Oracle` 's syntax does not support keyword `if exists`, creating `berry.meta`, dropping table, and creating view's `if exists` should be replaced to `pl/sql`. (Raw Data / Meta Data)
`limit` | In `Oracle` `fetch first n rows` is equivalent to `limit`(Raw Data/Meta Data)
`replace into` | `replace in to` is used when creating a view in the database. `merge into` can be used in `Oracle instead` (Raw Data / Meta Data)
`group by` | In `MySQL` the select clause executes first, but in `Oracle` where clause executes first. Changes in the function of parsing group by. (Raw Data)
Extracting time units | In `MySQL` there are functions to extract a certain time field, and the usage in `Oracle` is different. (Raw Data)
Full text search |  Different syntax (Raw Data)
Adding quotations | Currently, names such as `berry.meta`, `stats.creatTime` are all using quotations to correspond to `AsterixDB`(Same in `MySQL`) (Meta Data / Raw Data) 
## Functions overrode
- `parseTimeRelation`
- `parseTextRelation`
- `parseDrop`
- `parseCreate`
- `parseSelect`
- `parseGroupByFunc`
- `parseGroupBy`
- `parseUpssertMeta`
- `fieldType2SQLType`

# New issue found

`select tt."county" as "county",tt."count" as "count",ll0."population" as "population"
from (
select "geo_tag.countyID" as "county",count(*) as "count"
from "twitter.ds_tweet_56ab24c15b72a457069c5ea42fcfc640" t
where t."create_at" >= to_date('2018-01-02 00:00:00','YYYY-MM-DD HH24:MI:SS') and t."create_at" < to_date('2018-01-04 00:00:00','YYYY-MM-DD HH24:MI:SS') and t."geo_tag.countyID" in ( more than 1000 county IDs )
group by "geo_tag.countyID"
) tt left outer join "twitter.dsCountyPopulation" ll0 on ll0."countyID" = tt."county";`

Oracle does not allow a query's list exceed 1000 elements. This will happen when we zoom twittermap's screen to a place more than 1000 counties.
## Solutions proposed by Taewoo
1. To change the query to state level instead of county
2. To set a restriction that when the elements in the list exceeds 1000, only query on those 1000 couties.

**Comment by chenlica** [comment]
@taoenkh @baiqiushi should we close it?
