### ISSUE TITLE
Evaluate: Greenplum

### ISSUE THREAD

**Issue by dayuebai** [ISG-ICS/cloudberry#577]
# Overview
This issue aims to evaluate: [Greenplum](http://greenplum.org), an advanced, fully-featured, and open source data warehouse.

# Authors
Dayue Bai (advised by Prof. Chen Li), late August 2018

# Reference
- [Greenplum Database Documentation](https://greenplum.org/docs/5100/common/gpdb-features.html)

- [Greenplum database repository on Github](https://github.com/greenplum-db/gpdb)

- [GPORCA repository on Github](https://github.com/greenplum-db/gporca)

- [PostgreSQL Database Documentation](https://www.postgresql.org/docs/)

- [Evaluation of Elasticsearch](https://github.com/ISG-ICS/cloudberry/issues/568) (Issue 568)

- [Evaluation of Druid + Superset](https://github.com/ISG-ICS/cloudberry/issues/546) (Issue 546)

# Background
Greenplum, a division of [Pivotal Software, Inc.](https://pivotal.io/), focuses on big data analytics. It was founded in September 2003, as two small companies (Metapa and Didera) merges. In 2005, Greenplum released its DBMS software: Bizgres based on [PostgreSQL](https://www.postgresql.org/) (an Object RDBMS). In July 2010, Greenplum was acquired by Dell EMC. After Pivotal Software spin out of Dell EMC, this database system is known as **Pivotal Greenplum Database**. Now it is developed by both Greenplum Database [open source community](https://github.com/greenplum-db/gpdb) and Pivotal software. The main feature of Greenplum is massively parallel processing architecture (MPP). Its competitors include other MPP vendors including [Amazon Redshift](https://aws.amazon.com/redshift/), [Microsoft Azure](https://azure.microsoft.com/en-us/) and other data warehouse vendors such as [IBM DB2](https://www.ibm.com/analytics/us/en/db2/) and [SAP HANA](https://www.sap.com/developer/topics/sap-hana.html).

### PostgreSQL
[PostgreSQL](https://www.postgresql.org/) is an object-relational database management system (ORDBMS), developed at the University of California, Berkeley. It is the default database for macOS server and available for Linux and Microsoft Window, as well. It supports most parts of the SQL standard and offers many modern features such as triggers and transactional concurrency. It is open source and free to modify and distribute.

- Initial release: 07/08/1996 (22 years ago)

- Latest stable release: 08/09/2018 (version 10.5 & 11 Beta 3)

- Language: C

- OS: UNIX-like OS & Microsoft Windows

# Basic Info
- Initial release: April 2005 (13 years ago)

- Latest release: 08/09/2018 (version 5.10.2)

- Merged with: PostgreSQL 9.2beta2

- OS: Linux & macOS

- Type: data warehouse

- License: Apache 2 License

# Architecture
![screen shot 2018-08-27 at 10 58 51 pm](https://user-images.githubusercontent.com/27508202/44703524-cd18ef80-aa4c-11e8-965a-6cc69b281980.png)

# Basic Concepts
**Data warehouse**

Greenplum is an OLAP data warehouse, which exists as a layer on top of another database (usually OLTP database). Greenplum provides a layer on top of an array of individual PostgreSQL databases. 

- On the top layer, it provides a master host for a client to connect and submit SQL statements. 

- On the top layer, it also provides a network layer for the master host to distribute workloads to each segment. In this way, it behaves as one logical database. 

- Greenplum also modifies the internals of PostgreSQL, especially providing a **cost-based query optimizer** to deal with big data analytics.

**Master**

The master host is the **entry** to the Greenplum DB, accepting client connections and SQL queries, and distributing the workload to segment instances.

**Segment**

Greenplum DB is essentially several PostgreSQL database instances (segments) acting together as one cohesive DBMS. 

- Each segment instance stores a **distinct** portion of the data and perform query processing. 

- User-defined tables and indexes are distributed across segments.

- Users have the choice of choosing fields to distribute data across segments or distribute randomly. For best query performance, all segments handle an even share of the query workload.

**Interconnect**

Greenplum Interconnect is the networking layer of the Greenplum DBMS. It refers to the inter-process communication between segments and network infrastructures such as switches. It uses a protocol that is more reliable than UDP and more scalable and faster than TCP.

**Mirror segments**

For high availability, Greenplum DBMS lets users configure mirror segments in case queries fail. The mirror segment should reside on a different host than its primary segment. When the primary segments are unavailable, Greenplum DBMS will automatically bring up mirror segments to the place.

# Features
**Massively parallel processing (MPP)**

- Refers to a system with 2 or more processors that cooperate to carry out an operation.

- Each processor with its own OS, memory and disk storage.

- Use all of a cluster's resources in parallel to process a query. The master host distributes workloads to each segment.

**Cost-based query optimizer**

- [GPORCA](https://github.com/greenplum-db/gporca) is the cost-based query optimizer, leveraged for query planning.

- Different from PostgreSQL's query planner. Customized to handle big data analytics.

**High availability & scalability**

- Mirror segments mechanism ensures high availability when a query fails.

- Interconnect networking layers provides User Datagram Protocol with flow control (UDPIFC), which can extend much more segment instances than traditional Transmission Control Protocol (TCP).

**Greenplum Database Access**

Under Greenplum MPP architecture, a client always connects to the database through the *master* host.

- Native Client Applications: Installed with client utility applications such as psql (CLI)

- Standard Application Interface: provided by PostgreSQL; including ODBC, **JDBC**, Perl DBI, Python DBI, libpq C Library

- RESTful API: third-party RESTful API for connection

- Support Database connection pooling with [PgBouncer](https://pgbouncer.github.io/) (a connection pool manager for Greenplum)

**Semistructured Data Model Support**

As an OLTP data warehouse, Greenplum DB provides gpfdist parallel file server for users to set up a transformation that enables gpdb external tables to read semistructured files such as JSON and XML.

- An input transformation reads a file in non-natively supported format and outputs rows to the gpfdist file server in text or CSV format.

- A configuration file for data format transformation is required.

**Full-Text Search**

- Users can use full-text search built in PostgreSQL.

- Pivotal also provides a system named [GPText](https://gptext.docs.pivotal.io/200/topics/intro.html) which combines Greenplum DB cluster with Apache SolrCloud cluster to do text analytics.

**Polymorphic Storage Model**

Greenplum Database supports several storage models and a mix of storage models. When creating tables, users can choose storage models.

Heap storage: 

- default storage model in PostgreSQL. 

- Require row orientation store. 

- Support UPDATE and DELETE. 

- Suitable for small size tables with more transaction processing (OLTP queries).

- NOT support compression

Append-Optimized storage (AO): 

- Eliminate overhead of update visibility information (save storage)

- The only storage model that supports **column-oriented** table (column store)

- Support different compression schemes

- Optimized for bulk data loading

- Suitable for analytical queries (queries not involving data modification)

- Support UPDATE and DELETE (for queries with snapshot isolation)

**Row/column-oriented Storage**

Greenplum provides users with storage orientation models: row, column, and a mix of both models.

Row-oriented storage:

- Good for OLTP queries

- Good for table updated, inserted and deleted frequently (In column store database, column values of a row are in different places on disk)

- Good for queries involving a large number of columns (for the same reason mentioned above)

Column-oriented storage:

- Good for OLAP queries (queried usually used in business intelligence industry)

- Easy to support semistructured data model such as JSON and XML (no need to maintain some metadata constraint)

- Easy to compress (data in a single column is of same data type)

- Good for aggregation or read over a small number of columns 

- Poor at updating, deleting, and reading many columns at the same time.

**Table Partitioning**

Table partitioning divides a table into smaller pieces based on range or list of values, or both.  

- Physically partition tables across segments to enable MPP

- Improve query performance by allowing scanning only the data needed rather than the entire table contents.

- Easy to maintain data warehouse such as rolling old data out of the data warehouse (for example, drop certain table partition by time range)

- Can alter partition design after tables are created

Multi-level Partition Design Example:

![screen shot 2018-08-28 at 1 45 15 am](https://user-images.githubusercontent.com/27508202/44711789-0ad54280-aa64-11e8-8ae2-93a59d814fd8.png)

**Index**

Unlike a traditional database, indexes in Greenplum DB should rarely be used.

- Indexes locate records in a random pattern. In Greenplum DB, data is distributed and partitioned across segments so each segment only stores a small portion of data. With many segments, using indexes is not efficient.

- Improve performance of OLTP queries which return a smaller subset of data, while OLTP queries usually retrieve a larger subset of data. 

**External Table**

An external table is a table pointing to data that is stored outside of the Greenplum DB, so an external table is readable and writable. It can be used with SQL commands.

An external table can be accessed via HTTP server, so users can load data source stored outside Greenplum DB. Data can be first read into an external table and then inserted into a table of Greenplum DB. 

- Supported data source: local file system, HDFS data, JSON, CSV, and more.

- Load large-scale data in high speed

# Installation Issue
On macOS, when building GPORCA (the cost-based query optimizer) with dependency (Conan: a C/C++ package manager written in Python), the Python program throws an exception. Users can choose to build GPORCA manually and then build the Greenplum database.

For details related to the error of dependency, please refer to [Issue 5579](https://github.com/greenplum-db/gpdb/issues/5579) under GPDB Github repository and [Issue 375](https://github.com/greenplum-db/gporca/issues/375) under GPORCA Github repository.

# Testing
### Testing Machine
- Machine: MacBook Air (13-inch, Early 2015)
- Architecture: x86 64-bit
- CPU: 1.6 GHz Intel Core i5
- Memory: 8 GB 1600 MHz DDR3
- Storage: 128GB PCIe-based SSD
- OS: macOS High Sierra Version 10.13.6

### Testing GPDB Version
- Testing version: gpdb 5.10.2
- Compiled by: Apple LLVM version 9.1.0 (clang-902.0.39.2)

### Testing Data Source & GPDB Configuration
<table>
<tr>
<td>Data Source</td><td colspan="4">Twitter</td>
</tr>
<tr>
<td>Fields (type)</td><td colspan="4">create_at (timestamp), id (bigint), text (text), stateID (int), countyID (int), cityID (int) (6 fields in total)</td>
</tr>
<tr>
<td>Number of records</td><td>47,000 (47K)</td><td>1,483,353 (~1.4M)</td><td>14,599,988 (~14.6M)</td><td>52,252,291 (~52.2M)</td>
</tr>
<tr>
<td>Original file size (uncompressed)</td><td>6.2 MB</td><td>203 MB</td><td>2.02 GB (~2068.48 MB)</td><td>7.2 GB (~7372.8 MB)</td>
</tr>
<tr>
<td>Original file format</td><td colspan="4">CSV</td>
</tr>
<tr>
<td>Segment</td><td colspan="4">One segment host (local host) with 5 segments</td>
</tr>
<tr>
<td>Storage model</td><td colspan="4">Append Optimized (AO) & column store</td>
</tr>
<tr>
<td>Compression types</td><td colspan="4">ZLIB</td>
</tr>
<tr>
<td>Compression level</td><td colspan="4">Level 5</td>
</tr>
<tr>
<td>Distributed by</td><td colspan="4">create_at (data type: timestamp)</td>
</tr>
<tr>
<td>Table Partioning</td><td colspan="4">False</td>
<tr>
</table>

### Data Loading Time
The table below shows the time to load each data source into Greenplum DB.

- Using indexes: NO
- Using external table: YES
- Using protocol: file: // (load file in local machine)
- Loading time doesn't include time for creating index.

| Table | ~52.2M tweets | ~14.6M tweets | ~1.4M tweets | 47000 tweets |
|-------|:--------------:|:--------------:|:---------------:|--------------|
| Loading Time | 315 sec (5 min 15 sec) | 79.5 sec | 8.9 sec | 1.3 sec |

From the data shown above in the table, Greenplum loads large-scale data (to ~52M records) in high speed, with an external table.

### Storage
This Table shows the disk size of each testing data source (not include index file) stored in Greenplum DB, compared with original file size.

- Including index file size: NO

| Disk size / Data source | ~52.2M tweets records |~14.6M tweets records  | ~1.4M tweets records | 47000 tweets records |
|-------------------|:-------------:|:------------:|:-------------:|------------------------------------|
| Disk size | 5.2 GB | 734.4 MB | 73.8 MB | 2.5 MB |
| Original file size | 9.02 GB | 2.02 GB | 203 MB | 6.2 MB |

### Building Index
Index can be used to speed up full-text search but is not necessary for full-text searching.

Using index: YES, building index on ```text``` field to speed up full-text searches.

Index type: GIN (Generalized Inverted Index)-based index (as opposed to Generalized Search Tree-based index).

| Table | Total indexing time (building index included) | Table disk size | Index disk size | Total disk size | Original file size | Compression rate |
|------|:--------------------:|:---------------:|:--------------:|:--------------:|:--------:|------------|
|47,000 tweets | 2.1 sec | 2.5 MB | 9.75 MB | 12.25 MB | 6.2 MB | 197.58% |
| ~1.4M tweets | 31.9 sec | 73.8 MB | 214.1 MB | 287.9 MB | 203 MB | 141.82 % |
| ~14.6M tweets | 371.1 sec (6.185 min) | 734.4 MB | 1.73 GB (1773.4 MB) | 2.45GB (2507.8 MB) | 2.02 GB | 121.29% |
| ~52.2M tweets | 2137.8 sec (35.63 min) | 2.55GB (2610.4 MB) | 5.8 (5945.1 MB)| 8.35 GB (8550.4 MB) | 7.2 GB (~7372.8 MB) | 115.97% |

Compared with Elasticsearch:

| Table | Total indexing time (building index included) | Total disk size | Original file size | Compression rate |
|------|:-------------------------------------------:|:-------------:|:-----------------:|---------------|
| 47000 tweets | 4.1 sec | 18.7 MB | 14.5 MB | 128.97% |
| 1.4M tweets | 6 min | 570.1 MB | 470.9 MB | 121.06% |
| 14.6M tweets | 15 min | 5.3 GB | 4.67 GB | 113.49% |
| 52.2M tweets | 75 min | 19 GB | 17.27 GB | 110.02% |

*NOTE*:

* The original files used to test Elasticsearch and Greenplum are different. Only focus on data compression rate and how indexing time change as data volume becomes larger.

* In terms of data compression rate, Greenplum is not as good as Elasticsearch(index file included).

* In Greenplum, size of regular indexes is larger than the size of data stored in the table. With bitmap index, size of index file can be compressed. However, the bitmap index is poor at filtering column with high cardinality data (such as ```text``` field in Twitter data set).

### Query Performance
**Testing query templates for keyword searching**:

Using index: YES

1. ```SELECT date(create_at), count(*) FROM twitter WHERE text @@ to_tsquery('keyword') GROUP BY date(create_at) ORDER BY date(create_at);```

2. ```SELECT geo ID, count(*) FROM twitter WHERE text @@ to_tsquery('keyword') GROUP BY geo ID;```

**Testing query templates (NO keyword search)**: 

3. ```SELECT date(create_at), count(*) FROM twitter GROUP BY date(create_at) ORDER BY date(create_at);```

4. ``` SELECT geo ID, count(*) FROM twitter GROUP BY geo ID;```

**Selectivity**

Selectivity of each keywords in each data source:

| Keyword / Data source | ~52.2M tweets (01/24/2017 ~ 09/09/2017, ~9 months) | ~14.6M tweets (07/01/2017 ~ 09/01/2017, 2 months) | ~1.4M tweets (07/01/2017 ~ 07/07/2017, 1 week) |
|-----------------------|:----------------------:|:----------------------:|-----------|
| hurricane| 0.0365% (19,080/~52.2M) | 0.0693% (10115/14.6M)| 0.0076% (112/~1.4M) |
| Trump | 0.7267% (379,741/~52.2M) | 0.6641% (96,953/14.6M) | 0.6013% (8,920/~1.4M) |
| love | 2.6961% (1,408,753/52.2M) | 2.7309% (398,712/14.6M) | 2.6769% (39,708/~1.4M) |

**Keyword Search (Full-text search)**

* Testing query 1 (Filter by text & Group by day)

| Keyword / Data source | ~14.6M tweets (07/01/2017 ~ 09/01/2017, 2 months) | ~1.4M tweets (07/01/2017 ~ 07/07/2017, 1 week) |
|-----------------------|:-----------------------:|-----------|
| hurricane| 114.5 sec | 11.3 sec |
| Trump |115.2 sec | 11.4 sec |
| love | 117.1 sec | 13.4 sec |

Compared with the same measure of Elasticsearch:

| Keyword / Data source | ~52.2M tweets (01/24/2017 ~ 09/09/2017, ~9 months) | 14.6M tweets (07/01/2017 ~ 09/01/2017, 2 months) | ~1.4M tweets (07/01/2017 ~ 07/07/2017, 1 week) |
|-----------------------|:----------------------:|:----------------------:|-----------|
| hurricane| 0.216 sec | 0.165 sec | 0.112 sec |
| Trump | 0.443 sec | 0.274 sec | 0.161 sec |
| love | 1.070 sec | 0.407 sec | 0.211 sec |

* Testing query 2a (Filter by text & Group by city ID)

| Keyword / Data source | ~14.6M tweets (07/01/2017 ~ 09/01/2017, 2 months) | ~1.4M tweets (07/01/2017 ~ 07/07/2017, 1 week) |
|-----------------------|:-----------------------:|-----------|
| hurricane| 117.1 sec | 11.8 sec |
| Trump | 120.8 sec | 12.5 sec |
| love | 122.1 sec | 15.9 sec |

Compared with the same measure of Elasticsearch:

| Keyword / Data source | ~52.2M tweets records | 14.6M tweets records | ~1.4M tweets records |
|-----------------------|:----------------------:|:----------------------:|---------|
| hurricane| 0.422 sec | 0.351 sec | 0.170 sec |
| Trump | 0.718 sec | 0.414 sec | 0.284 sec |
| love | 1.630 sec | 0.996 sec| 0.427 sec |

* Testing query 2b (Filter by text & Group by state ID)

| Keyword / Data source | ~14.6M tweets (07/01/2017 ~ 09/01/2017, 2 months) | ~1.4M tweets (07/01/2017 ~ 07/07/2017, 1 week) |
|-----------------------|:-----------------------:|-----------|
| hurricane| 105.3 sec | 11.3 sec |
| Trump | 107.1 sec | 11.5 sec |
| love | 114.5 sec | 13.8 sec |

Compared with the same measure of Elasticsearch:

| Keyword / Data source | ~52.2M tweets records | 14.6M tweets records | ~1.4M tweets records |
|-----------------------|:----------------------:|:----------------------:|------|
| hurricane| 0.181 sec | 0.158 sec | 0.154 sec |
| Trump | 0.263 sec | 0.192 sec | 0.171 sec |
| love | 0.269 sec | 0.263 sec | 0.177 sec |

**NO Keyword Search**

* Testing query 3 (Count tweets & NO keyword search & Group by day)

| Table | ~52.2M tweets (01/24/2017 ~ 09/09/2017, ~9 months) | ~14.6M tweets (07/01/2017 ~ 09/01/2017, 2 months) | ~1.4M tweets (07/01/2017 ~ 07/07/2017, 1 week) |
|-------------------|:-----------:|:------------:|----------------------------|
| Greenplum | 11.359 sec | 3.181 sec | 0.426 sec |
| Elasticsearch | 2.079 sec | 1.214 sec | 0.352 sec |
| Druid | N/A | N/A | 1.959 sec |
| AsterixDB | N/A | N/A | 18.625 sec |

* Testing query 4 (Count tweets & NO keyword search & Group by city ID)

| Table |  ~52.2M tweets records | ~14.6M tweets records | ~1.4M tweets records |
|-------------------|:-----------:|:------------:|----------------------------|
| Greenplum | 9.370 sec | 2.577 sec | 0.381 sec |
| Elasticsearch | 5.982 sec | 1.591 sec | 0.719 sec |
| Druid | N/A | 6.155 sec | 1.688 sec | 

# Conclusion
<table>
<tr>
<td>Table</td><td>Pros</td><td>Cons</td>
</tr>
<tr>
<td>Greenplum Database</td>
<td>
<ul>
<li>Quick to load large scale data (not building index) with AO storage model</li>
<li>High availability & scalability</li>
<li>Support semistructured data model</li>
<li>Polymorphic storage choice</li>
<li>Customized table partition and distribution across segments</li>
<li>Compress data with AO storage model & column store & compression algorithm</li>
<li>Aggregation query (NO search) performance better than Druid, worse than Elasticsearch</li>
</ul>
</td>
<td>
<ul>
<li>Poor at doing text searching</li>
<li>Size of index file larger than data (building regular index)</li>
<li>Lower data compression rate than Elasticsearch</li>
<ul>
</td>
</table>

**Comment by chenlica** [comment]
@dayuebai please close it if it's done.

**Comment by dayuebai** [comment]
Sure
