### ISSUE TITLE
Add an api for Cloudberry to check the existence of view

### ISSUE THREAD

**Issue by lengyyy** [ISG-ICS/cloudberry#585]
## Overview
- For **Coundberry Server**: it aims to add a new **api** so that Twittermap server can check whether a query can solve by view (cached result) or not.
- For **Twittermap application**: it aims to **disable** the button of sidebar when view is not established. And enable sidebar when query can solved by the view. It can improve the user experience about content in the sidebar.
#### For cloudberry
-  **RequestRouter.scala**
 Make the name of client and other variable names more general.
- **Cloudberry.scala** 
Add new web socket for checking whether a query can be solved by view.
- **routes**
Add address for new api in routes
- **JsonParser.scala**
Add a function to get queryID
- **QueryPlanner.scala**
Add a function to return whether there is matched views for a query.
 Extract a function to find the matched views for a query.
- **ViewStatusClientTest.scala**
Three tests for ViewSatusClient.
- **ViewStatusClient.scala**
**1.** This is a reactive client which checks whether a query can be solved by the existed view.
**2.** When client receiving message: parse the json to queries, and for each query let planner to decide  whether it can be solved by view. 
**3.** Return the "isQuerySolvableByView" result with queryID to frontend

 #### For twittermap
-  **TwitterMapApplication.scala**
Add a WebSocket that send query to Cloudberry
- **application.conf**, **common/services.js**, **routes**
Add related address for new api
- **index.scala.html** 
Add id for sidebar button.
- **sidebar/controllers.js**
**1.** Add a WebSocket that send query to Cloudberry
**2.** When the keywords changed, we need to: clear previous timer, close and disable sidebar, and set a new timer for new keywords. The timer sends query to check whether it is solvable, every one second.
**3.** When receiving messages from websocket, check its queryID and result. If queryID is matched and result is true, enable the sidebar button and clear timer.

## Result
In this demo: 
- "code" is a keyword without cached view
- "water" is a keyword already cached.

![imageedit_1_7641184993](https://user-images.githubusercontent.com/26839941/44494410-72346200-a620-11e8-91b8-e0b309b15cb9.gif)

## Resources
To add an api to Cloudberry, and let Twittermap communicate with it, some related document of the [Play Framework](https://www.playframework.com/documentation/2.5.x/ScalaWebSockets), and [akka Framework](https://doc.akka.io/docs/akka/2.5/guide/tutorial.html) may be help.

## To Do List
- [x] ~~Add a socket in Twittermap to sent query to Cloudberry~~
- [x] ~~Add a entry in Cloudberry to receive the query from client~~
- [x] ~~Add a ViewStatusClient in Cloudberry to check whether a query can solve by view~~
- [x] ~~Disable sidebar button when view not exists~~
- [x] ~~Set timer to send query~~
- [x] Add feature into Cloudberry

**Comment by baiqiushi** [comment]
#588
