### ISSUE TITLE
New popup window has no normalized count update.

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#593]
Our current production implementation about `normalize` feature is like this, when `normalize` button is `ON`, the top left toolbox will show the `count/Million` result for the state/county/city mouse over.
Looks like this:
![image](https://user-images.githubusercontent.com/8113414/45566885-ebcd0380-b80c-11e8-882d-9ce5808d2d3a.png)

But the new popup window implementation does not inherit this feature.

**Comment by lengyyy** [comment]
Add normalized count update to popup window.
![qq20180916-164507-hd](https://user-images.githubusercontent.com/26839941/45594596-36e34400-b9d0-11e8-975d-90f41a24e9ab.gif)

**Comment by baiqiushi** [comment]
#594
