### ISSUE TITLE
County level polygons are not removed when zoomed into city level

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#596]
# Problem
The county level polygons are not removed when zoomed into city level.
![image](https://user-images.githubusercontent.com/8113414/45794303-d4e24300-bc4a-11e8-9b00-62fb4c490c30.png)

**Comment by chenlica** [comment]
If I remember correctly, we kept the county-level polygons for the city level on purpose in order to show those county boundaries.  Make sure to talk to @waans11 for his input before making any changes.

**Comment by baiqiushi** [comment]
This behavior is supposed to be correct as designed.
