### ISSUE TITLE
Add Zip code layer

### ISSUE THREAD

**Issue by LeeEunah** [ISG-ICS/cloudberry#601]
[Updated 13/Nov/2018]
# U.S Twittermap
same work like Korean twittermap
### 1. Construct zip code data
- Collect [U.S zip code polygon datas](https://www.census.gov/geo/maps-data/data/cbf/cbf_zcta.html) from that link. Unfortunately, they don't have all of U.S zip codes.
- You should import .dbf, .prj, .shp and .shx file and export to GeoJson file through [mapshaper](https://mapshaper.org/).
  <img src="https://user-images.githubusercontent.com/29943356/48449855-c8fd9380-e758-11e8-947d-4831e1614b33.png" width="250">

- The zip code polygon datas only include zip code and geoID property. For Cloudberry zip code layer, the data should include the state and  county information.  
<img src="https://user-images.githubusercontent.com/29943356/48450093-c3ed1400-e759-11e8-9256-cb87af39b8db.png" width="250">  

- I found an [csv file](http://federalgovernmentzipcodes.us/) that include zip code, state name and city name. And construct the properties of zip code data using the csv file and city json data of Cloudberry.
<img src="https://user-images.githubusercontent.com/29943356/48451034-7c688700-e75d-11e8-9019-1ff99334f80f.png" width="200">

[TO DO]
- [ ] Collect more zip code polygon datas.

### 2. Draw zip code polygons
**City layer doesn't exist on my code.**
- Add 'zipcode.json' file in **examples/twittermap/web/public/data** path
- **TwitterMapApplication.scala**
   Add functions to load, find and get zip code datas
- **application.conf**
Add the zipcode file path
- **controller.js & countmap.js**: 
Add the zipcodeStyle that defines the style of polygons.
- **controller.js**: 
When the map zoomed, the zip code layer appears on map. 
And load geoJson to get zip code polygons.

![image](https://user-images.githubusercontent.com/29943356/48451547-c488a900-e75f-11e8-82ff-02a6aeea32c4.png)

### 3. Make geotag datas
- **geotag.sh**
Add zipcode file path
- **IUSGeoJSONEntity.scala**
Add zip code entity
- **USGeoGnosis.scala**
Zip code datas don't have any city information in their properties. So 'tagCity' function is useless.
- **package.scala**
Add the TypeLevel of zip code.
- **TwitterJSONTagToADM.scala**
Add the case of zip code
- **Tweet.java**
Random coordinates are given for null value of coordinates.  
The 'textMatchPlace' function is useless, because zip code datas don't have any city information.
- Some of tweet doesn't have any coordinate value. If the coordinate is not assigned, this tweet is useless. So random coordinates are given using the bounding box.
  <img src="https://user-images.githubusercontent.com/29943356/49638840-c129ca00-fa4c-11e8-9ec4-36773478bee6.png" width="250">

-------------------
# Korean Twittermap
**1. Construct zip code data**
- Match data format with Cloudberry.
- Simplify zip code data because of big size.

**2. Draw zip code polygons**
- Included the zipcode.json path into codebase.
- Zip code layer is also stored in cache like city layer.
![image](https://user-images.githubusercontent.com/29943356/46238590-5f5d2d80-c342-11e8-8d11-0638fd8840d0.png)

------------------
[TO DO]

- [x] Designate random coordinates to Korea datas. (Korean datas don't have any city information.)

- [ ] How to switch city and zip code layer.

**Comment by chenlica** [comment]
@waans11 @baiqiushi status?  close it?

**Comment by baiqiushi** [comment]
The work has been archived into branch `zipcode` for future reference.
