### ISSUE TITLE
Disabling TwitterMap popup window before users submit a query

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#602]
Currently if the user doesn't submit a keyword, when we hover the mouse over a state, it shows "Count 0", which is misleading.  See the following screenshot.  It will be good if we can enable the popup window only if the user has typed in a keyword.
<img width="548" alt="screen shot 2018-10-09 at 11 42 17 am" src="https://user-images.githubusercontent.com/12926365/46691610-2894dc00-cbba-11e8-8428-5a5eeb20206d.png">

**Comment by baiqiushi** [comment]
#604
