### ISSUE TITLE
Support list of stateful values inside cloudberry merger module

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#606]
# Overview

  Current Cloudberry does not support aggregation functions that need more than one values to calculate, such as `average` and `top-k`. The reason is that current interface of mergers inside Cloudberry only takes one attribute from the cached relation.

**Comment by chenlica** [comment]
@baiqiushi status?  close it?

**Comment by baiqiushi** [comment]
Instead of implementing a general solution, this #626 PR uses a simple way to resolve the AVG problem temporarily. This issue is low priority for now.
