### ISSUE TITLE
Cloudberry return partial result rather than aggregate result

### ISSUE THREAD

**Issue by AC-Unicorn** [ISG-ICS/cloudberry#609]
### Issue description:
In our current design of cloudberry, every time cloudberry received a mini-query result, we will merge the partial result with the aggregated previous partial results, then send it back to frontend. This methodology is valid, however inefficient when aggregated results getting larger. So Now we wanna return partial result every time rather the aggregated result.

![image](https://user-images.githubusercontent.com/10699892/48037900-34c17a00-e123-11e8-8f08-3561b41ede54.png)

### Query Workflow:
![image](https://user-images.githubusercontent.com/10699892/48037797-d1374c80-e122-11e8-8801-de66babb06bd.png)

### Check List:
- [x] Experiment and prototyping 

- [x] Testing and validation

- [x] Implementation

**Comment by chenlica** [comment]
@AC-Unicorn  Please close this issue after its done.
