### ISSUE TITLE
[FE] [webGL] 

### ISSUE THREAD

**Issue by ruig2** [ISG-ICS/cloudberry#624]
The points in the hidden color-to-id layer may overlap. WebGL would draw points in squares, and the edge between the circle and the square may overwrite other circles per the following figure shows.

This is not serious in the production environment because the points there would be pretty small.

cc @baiqiushi 

![image](https://user-images.githubusercontent.com/41367284/48978055-b9d0ec80-f05a-11e8-829c-74152595fb50.png)

**Comment by chenlica** [comment]
Let's discuss F2F in our meeting on Monday.
