### ISSUE TITLE
[Meta Issue] List of software packages and algorithms to verify

### ISSUE THREAD

**Issue by ruig2** [ISG-ICS/cloudberry#642]
This is a meta issue which lists all the software packages and algorithms that we'd like to verify. If we find something (either software or algorithm) interesting and want to verify if it works to integrate it into our own system, then let's create a **separated** new issue and add the link of the new issue here.

The following is the list of software packages to verify:

| Name                                                  | Type (software or algorithm) | Related Github issue                             | Reference                                |   |
|-------------------------------------------------------|------------------------------|--------------------------------------------------|------------------------------------------|---|
| OntoVis: algorithms to visualize social network       | Algorithm                    | https://github.com/ISG-ICS/cloudberry/issues/641 | Paper by Ma and Muelder in Computer 2013 |   |
| Layout algorithms to visualize a dynamic dataset      | Algorithm                    | https://github.com/ISG-ICS/cloudberry/issues/640 | Paper by Ma and Muelder in Computer 2013 |   |
| Analytical or approximate solutions for big graph viz | Algorithm                    | https://github.com/ISG-ICS/cloudberry/issues/639 | Paper by Ma and Muelder in Computer 2013 |   |

**Comment by baiqiushi** [comment]
Deprecated.
