### ISSUE TITLE
Evaluating graph embedding software

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#644]
Todo: evaluate existing open source software packages to do graph embedding.

**Comment by vichgy** [comment]
This paper (https://www.theoj.org/joss-papers/joss.00876/10.21105.joss.00876.pdf) mentioned the GEM, the python package for graph embedding methods with the GitHub source https://github.com/palash1992/GEM

**Comment by vichgy** [comment]
Beside static Graph embedding, there is also a dynamic graph embedding called DynamicGEM(https://github.com/palash1992/DynamicGEM). It implemented Incremental SVD, Rerun SVD, Optimal SVD, Dynamic TRIAD, Static AE, Dynamic AE, Dynamic RNN, Dynamic AERNN.

**Comment by vichgy** [comment]
![image](https://user-images.githubusercontent.com/32085429/54251172-a6f80000-4503-11e9-8dbd-34c72c384fb2.png)
![image](https://user-images.githubusercontent.com/32085429/54251226-cdb63680-4503-11e9-885b-2967e5a6806b.png)

**Comment by vichgy** [comment]
Wolfram has a function to deal with planar embedding. Which makes sure that there is no crossing for the graph. 
![image](https://user-images.githubusercontent.com/32085429/54251267-e9b9d800-4503-11e9-8f85-ba9400f34891.png)

**Comment by vichgy** [comment]
There is a built-in function in the Wolfram. https://docs.google.com/document/d/1VmevzMOBsi9gRvZFljDAWMtgN8AqJPiSQNMjYLh-vBQ/edit?usp=sharing
In the function, it will shuffle the vertices in order to get rid of crossing edges.

**Comment by chenlica** [comment]
Please write a high-level summary of this work (in addition to those links) before we close this issue.

**Comment by vichgy** [comment]
A graph embedding is a particular drawing of a graph. For this issue, we focus on drawing the planar embedding. We want to create a planar graph,  which can be drawn on the plane in such a way that its edges intersect only at their endpoints. 
Link of graph embedding:
http://mathworld.wolfram.com/GraphEmbedding.html
Link of PlanrDrawing:
http://mathworld.wolfram.com/PlanarDrawing.html
Link for A discussion about how to create a better planar graph:
https://community.wolfram.com/groups/-/m/t/1074975
Link of planar embedding in the C++ Boost Library:
https://www.boost.org/doc/libs/1_55_0/libs/graph/doc/PlanarEmbedding.html

**Comment by chenlica** [comment]
Thanks for the summary.
