### ISSUE TITLE
Collecting tweets related to Zika

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#65]
We want to collect tweets related to Zika.  We can start by doing the following:

- @JavierJia  shares with Monique his existing code to collect tweets;

- Monique identifies Zika-related hashtags, and starts the automated process.  

- We need to decide where to put the tweets before analyzing and storing the info in AsterixDB.

**Comment by JavierJia** [comment]
@monimoledo

**Comment by JavierJia** [comment]
- [ ] read the Twitter Streaming API documents. 
- [ ] read the code in `TwitterFeedStreamDriver.java` and related code.
- [ ] try to copy the `streamFeed.sh` to run another tracking job for "zika" purpose only.
- [ ] research on the terms related with "zika"
- [ ] research on the other Twitter API to explore some historic data
