### ISSUE TITLE
Grafana InfluxDB Issue - stuck when data is large

### ISSUE THREAD

**Issue by heyhalcyon** [ISG-ICS/cloudberry#650]
## Problem
When we load a large amount InfluxDB data (i.e. 2.5 million, 165MB), Grafana will stuck and cannot show data at all. After several testing, the slow but manageable amount of data that Grafana could handle is about 40MB (650,000 data points).

## Plan 
All code are stored in https://github.com/JHaoX/Grafana-Influxdb
Our Final Report:
[Grafana.Research.Report.pdf](https://github.com/ISG-ICS/cloudberry/files/3245317/Grafana.Research.Report.pdf)

Our weekly progress and notes are in https://docs.google.com/document/d/1n134Bv2ykH8haWJdncO-He2slL8xXL_xn9JqGNiL7ZU/edit?usp=sharing

#### Step 1:
- [x] Figure out how Grafana interacts with Influxdb and why Grafana slows down. 
        - Grafana interacts with Influxdb using RESTFul API.
        - The transferred file is **json** style, encoded with **gzip**, and **Chunked** transfer encoding
        - The time spent on the internet transfer is around 3s (a query for 600,000), while rendering took almost 10s.
 
#### Step 2:
- [x] Develop a middleware between influxDB and Grafana. The middleware should get a request from Grafana and forward the request to InfluxDB, then retrieve the results from influxDB and send them back to Grafana.  

#### Step 3:
Optimize the middleware queries so that it will retrieve only a subset of data but the data shape will still looks similar. 
- [x] Implement the simple approach: After getting the data from influxDB using the original query, send only a fixed amount of data (i.e. 1500 points) by showing one point in each (total count/1500) points. <retrieving 2.6million data from the InfluxDB took about 4s>

- [x] Rewrite the query sent to DB when the data is large: retrieve only 2000 points from the influxDB by using random sampling.
Note: Using `GROUP BY` with mean takes the average of an interval, which may not represent the data correctly. Therefore, we chose to use random sampling.

- [x]  Record the query time and frontend rendering time on different sizes of databases, to see which part slows down the total process. Testing result is stored in the google doc above.
Observation: Frontend Grafana has a limitation on the amount of data it can display.

#### Step 4:
- [x] Analyze random sampling techniques
- Test random sampling on some real data sets that contain some pattern (Professor Eamonn Keogh may provide some time series data).  
- Visually compare the sample result with the original data set, and check if the sample keeps the original pattern.
- Give a conclusion about the reliability of random sampling on time series data.

- [x]  Intelligently decide the sampling ratio. 

- Idea: Try different sampling ratios, measure the similarity for each of the sampled dataset(using python SAX model). Decide a similarity lower bound. Find the lowest sampling ratio that meets the similarity requirement.
- Observation:
  - Data set with more obvious pattern has smaller distance, so it's hard to set a distance lower bound that's appropriate for ALL sizes of data sets.
  -  Therefore, a distance lower bound needs to be chosen for each data set. Below is our solution: (given that the max data size frontend can show without obvious delay is 12000)
    - For data set with  obvious pattern: choose the sample ratio with the smallest distance when the sample size <= 12000.
    - For data set with unobvious pattern: simply choose the largest sample size frontend can show, that is 12000.

**Comment by chenlica** [comment]
It may be a good time to understand "under the hood" of Grafana (since it's open source) before coming up with a solution.

**Comment by JHaoX** [comment]
Next steps working on this problem.

1.  Figure out how Grafana interacts with Influxdb and why Grafana slows down. 
    a. For Grafana, use browser Inspector to check the network. 
    b. For Influxdb, check the database log. 
    c. Also, check the source code on GitHub. 
2.  Literature search.
     Read the paper about interactive or approximate visualization of time series data. 
     And, analyze how existing software handles the visualization.

**Comment by JHaoX** [comment]
Status of the last object: 

1. Figure out how Grafana interacts with Influxdb and why Grafana slows down.
    a. Grafana interacts with Influxdb use RESTFul API. 
    b. The transferred file is **json** style file, encoded with **gzip**, and **Chunked** transfer encoding
    c. The time spent on the internet translation is around 3s (a query for 600,000), while the rendering takes near 10s. 

Task:
- Make a middleware between influxDB and Grafana: (may need Postman)
        Simulate a RESTful request sent by Grafana
        Modify the request to InfluxDB to retrieve a small amount (subset) of data, 
        Send the modified query data to Grafana

**Comment by JHaoX** [comment]
Grafana sends query frequently. When the user is typing, Grafana sends the unfinished query to the DB. 
For example, user want to make a query: "SELECT "degrees" FROM **"h2o_temperature"** WHERE $timeFilter". The Grafana may send a query like "SELECT "degrees" FROM **"h2o_"** WHERE $timeFilter".
This may hurt performance.

**Comment by JHaoX** [comment]
Task:
- Analyze random sampling
    1. Test random sampling on a real data set, which should contain some patterns (Professor Eamonn Keogh may provide some time series data).
    2. Visually compare the sample result with the original data set, and check if the sample keeps the original pattern.
    3. Give a conclusion about the reliability of random sampling on time series data.

Depends on the result of the analysis, we will do the following work:
If random sampling does not perform well, look for other sampling methods, and discuss the choice with Professor.
If it performs well, report the result and move on to the next step.

**Comment by JHaoX** [comment]
Result: 
  Random sampling did a good job at the data set with a clear pattern. For those data sets without a clear pattern, we decided to implement a method to measure similarity. 
Task:
  Find reasonable sample ratio for different data sets. (This can be done offline.)

**Comment by JHaoX** [comment]
Here is a pdf report for the current status.
[Grafana Research Report.pdf](https://github.com/ISG-ICS/cloudberry/files/3245273/Grafana.Research.Report.pdf)

**Comment by JHaoX** [comment]
Here is a pdf report for the current status.
[Grafana Research Report.pdf](https://github.com/ISG-ICS/cloudberry/files/3245296/Grafana.Research.Report.pdf)
