### ISSUE TITLE
Collecting Zika-related emails from ProMED

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#66]
http://www.promedmail.org/

Write a program to automatically retrieve Zika-related info from the service.

@JavierJia

**Comment by aishwaryakapse** [comment]
@aishwaryakapse

**Comment by chenlica** [comment]
@aishwaryakapse : welcome aboard!

**Comment by aishwaryakapse** [comment]
Crawljax crawler written in java worked for 2 pages of "http://www.promedmail.org".
Both BFS and DFS approach implemented.
Statistics and states stored in file system.
Error: org.openqa.selenium.WebDriverException: java.lang.InterruptedException: sleep interrupted.
