### ISSUE TITLE
Collect Zika-related information ProQuest Newsstand

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#67]
ProQuest Newsstand: http://www.proquest.com/products-services/globalnewsstream.html

@JavierJia

**Comment by xuxip** [comment]
ProQuest Newsstand search tool allows users to retrieve results from different subject areas and databases. 
 I requested a free trial for ProQuest Newsstand, I will get the response in the next few days.
Here is the 'search' tutorial:
https://www.youtube.com/watch?v=FPbAsS41bRA&index=1&list=PL-aFAdxOSTDdUyiF07Zu5t2XwpGjh-DID

**Comment by JavierJia** [comment]
Blocked.
