### ISSUE TITLE
Inverted Index in AsterixDB, PostgreSQL and Lucene

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#675]
![IMG_1724](https://user-images.githubusercontent.com/8113414/55608260-f14f5400-5732-11e9-81d4-87e72020696c.jpg)

## AsterixDB
 - Inverted Index is secondary index, where leafs are posting lists of primary keys (AsterixDB does NOT have fixed record IDs since they are periodically merged)
 - BTree stores entries with tokens as keys
 - Sorted heap file stores postings list
 - AND/OR operations will be done against secondary index scanning, then go to primary index for records

## PostgreSQL
 - Inverted Index is secondary index, where record ids are physical ids
 - BTree stores entries with tokens as keys
 - BTree stores long postings list or leaf page of entries BTree stores short postings list
 - AND/OR operations will be done by Bitmap Intersect/Union operations after Bitmap Scan of secondary index scanning, then scan heap file following Btimap of records/pages

## Lucene
 - Prefix-to-term-pointers list in first-level index
 - Term-to-postings-list-pointers list in second-level index
 - Sorted postings list with physical document ids in third-level index
 - AND/OR operations will be done with Intersect/Union operations agains lists of document ids

**Comment by chenlica** [comment]
Please ask Chen Luo and Zuozhi to confirm the details.

**Comment by luochen01** [comment]
Some clarification for AsterixDB:
We always use primary keys instead of record ids (records do not have fixed record ids since they are periodically merged).

**Comment by baiqiushi** [comment]
Done.
