### ISSUE TITLE
Hashtag Dashboard Proposal

### ISSUE THREAD

**Issue by yilei-wu** [ISG-ICS/cloudberry#687]
Our proposal is building a dashboard for the hashtag. User enter the dashboard in the side bar of the twittermap and trigger to zoom out the hashtag data bar into the dashboard. 

The features we plan to implement:
1. Display all the counts of hashtags in widgets correctly.
2. Each widgets can be selected.
3. Generate histogram for the selected widgets.
4. Generate various kinds of graphs(pie chart, line chart)
5. Other displays methods for further analysis

Possible Library:
d3.js
chart.js

**Comment by chenlica** [comment]
Please add some mockup drawings to show the design before doing the implementation.  Also can you change the github account name from "Elayyyyy" to your real name?

**Comment by Elayyyyy** [comment]
Ok professor, we will update with our UI design before tomorrow noon.

**Comment by yilei-wu** [comment]
Okay professor, we will update with our UI design before tomorrow noon.

**Comment by Brian-Jiang** [comment]
[design.pdf](https://github.com/ISG-ICS/cloudberry/files/3163334/default.pdf)

**Comment by chenlica** [comment]
Please present your design to the team in the meeting tomorrow.  Meanwhile, you can get familiar with the current codebase to see how to add these features step by step.

**Comment by baiqiushi** [comment]
Not needed anymore.
