### ISSUE TITLE
Regarding the Intellij configuration with SBT

### ISSUE THREAD

**Issue by HCWDavid** [ISG-ICS/cloudberry#689]
Found the solution to it by simply "import" your project with "build.sbt" inside of that folder. You do not need to import the entire folder. At the same time, if you don't have the configuration on the top right corner, just add configuration and add a template of "sbt". It should solve the problem

**Comment by chenlica** [comment]
@HCWDavid Can you change your github name to be consistent with your real name? :-)

**Comment by HCWDavid** [comment]
> @HCWDavid Can you change your github name to be consistent with your real name? :-)

My username is my initial ("Hanchen Wang") + my preferred name.. Sorry for the inconvenience. Do you still prefer me to alter my username to be more consistent? (I think the only way to do it is simply create a new user.) Thank you for the update :)

**Comment by chenlica** [comment]
You don't need to use another account. If there is a way to show an account name that's more recognizable, that will be great.  If not, that's fine.
