### ISSUE TITLE
AsterixDB Cluster - NC service heartbeat timeout

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#693]
## Problem
When deploying AsterixDB cluster on a **Large Memory** machine (e.g. ipubmed2, ochca, etc.), we tend to give **Large memory** budget to NC services (JVM arguments), at the same time, we need to add JVM arguments to set up the GC (Garbage Collection) behaviors properly, otherwise, JVM may trigger GC unpredictably and let GC run for a fairly long time during which the NC service process will be hang up, then the heartbeat to CC node will be timed out, leading CC node to kill the NC service finally. 

## Solution
In `cc.conf` under `ansible/conf`, add the following JVM arguments under `[nc]` configuration section.

```
[nc]
jvm.args=-Xmx72G -XX:ParallelGCThreads=8 -XX:ConcGCThreads=2 -XX:+UseG1GC -XX:MaxGCPauseMillis=500
```

At the same time, it would be better if we increase the heartbeat rate and the timeout threshold as following 2 parameters under `[cc]` configuration section in the same `cc.conf` file.

```
[cc]
heartbeat.max.misses=100
heartbeat.period=8000
```

**Comment by chenlica** [comment]
What's the solution to this problem?

**Comment by baiqiushi** [comment]
The JVM arguments line in the conf is the solution

**Comment by chenlica** [comment]
Please be more specific about the particular argument.

**Comment by baiqiushi** [comment]
OK. Modified.

**Comment by chenlica** [comment]
LGTM

**Comment by baiqiushi** [comment]
Done.
