### ISSUE TITLE
[Linux Server Maintenance] Ipubmed1-4 Ubuntu keyboard not working in login screen

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#724]
## Symptom
The `ipubmed3` machine was stuck at the login screen and keyboard was not responding after  a server restart. (Keyboard was working during BIOS phase and only stop working once the OS starts to boot)

## Solution
Reference: [Ubuntu 16.04 freezes on login screen, no keyboard or mouse working](https://askubuntu.com/questions/837003/ubuntu-16-04-freezes-on-login-screen-no-keyboard-or-mouse-working)

For our case, **First try to boot an old kernel** does not work because `shift` key does not work either once BIOS booting finishes;

So we need to follow the second option: **If you can't boot the machine at all**

(1) Follow this doc to setup an environment to be able to connect to `ipubmed3` using **iDRAC** remote control system.
[Using iDRAC to connect to ipubmed1-4 machines](https://docs.google.com/document/d/1SSqNnR9w9Rvs_n4MByjpIWUm_fFL2xtVkALFE4ptmdQ/edit?ts=5bde1e9e#heading=h.z3i2d8xy0p4y)

(2) Download a Ubuntu bootable ISO file (our case is [Ubuntu 14.04.6 LTS (Trusty Tahr)](http://releases.ubuntu.com/14.04/ubuntu-14.04.6-server-amd64.iso))

(3) Use iDRAC to launch a virtual console connecting to `ipubmed3`, and `F11` during BIOS booting to enter boot manager; Select `launch virtual media` inside the virtual console tool and select the Ubuntu ISO file as the media, click the `map` button to make the iso file on your local disk to be a virtual CD connected to `ipubmed3`; Then inside BIOS boot manager, select `Virtual CD` as the boot device;

(4) Enter Ubuntu Recovery mode (Select `Rescue a broken system` in the ubuntu boot menu)

(5) Select `em1` as the network interface when asked.

(6) Select `/dev/sdc4` as the root file system for launching a shell.

(7) Once enter the shell interface, the DNS may not work, meaning you can not do `apt update` or `apt upgrade`, then do the following to configure the DNS server (the same as other ipubmed machines)
```bash
rm /etc/resolv.conf
echo "nameserver 128.195.25.66" > /etc/resolv.conf
```
(8) If everything above works, just run the following command
```bash
apt update
```
```bash
apt upgrade
```
```bash
apt-get install --reinstall xserver-xorg-input-all
```
(9) Now just reboot the machine, the problem should be resolved.

**Comment by chenlica** [comment]
If the content in the Google Doc is not confidential, please include it in this issue to get rid of this external dependency.  Thank you.

**Comment by baiqiushi** [comment]
Done.
