### ISSUE TITLE
Show tweet-count trend and case-count trend in a popup window.

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#739]
### T1 Collect and ingest cases data into database.

Data source: [https://coronavirus.1point3acres.com/](https://coronavirus.1point3acres.com/).

#### T1.1 What is data format of data source?
Use csv for now, will transfer to database if later transfer to PostgreSQL. The current Asterix_db is not easy to maintain (ingest and query from it)

#### T1.2 Design our database schema.
Two csv files, representing States and Counties respectively. 

- [x] States: state_id, last_update, confirmed, new_confirmed, deaths, new_deaths, fatality_rate

- [x] Counties: county_id, last_update, confirmed, new_confirmed, deaths, new_deaths, fatality_rate

### T2 Show 2 line charts in one pop-up window of a polygon on Coropleth-map.

- [x] Twittermap web server coding.

- [x] Frontend coding.

**Comment by Yicong-Huang** [comment]
@JosephZheng1998 Can you please update the Issue description to match the new schema for csv files (states and cities)?

**Comment by JosephZheng1998** [comment]
Updated description

Data source: [COVID-19/Coronavirus Live Updates With Credible Sources in US and Canada](https://coronavirus.1point3acres.com)

T1.2 Design our database schema.

Two csv files, representing States and Counties respectively.

States: state_id, last_update, confirmed, new_confirmed, deaths, new_deaths, fatality_rate

Counties: county_id, last_update, confirmed, new_confirmed, deaths, new_deaths, fatality_rate
