### ISSUE TITLE
Collecting Zika-related information from healthmap.org

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#74]
http://www.healthmap.org/zika/#timeline

"It includes Zika epidemic timeline and spatial distribution.  There are also a lot of News links within the daily records."

@JavierJia  @MoniMoledo

**Comment by aishwaryakapse** [comment]
@aishwarya

**Comment by chenlica** [comment]
Based on a discussion with Public Health experts, we want to collect the following info: For each event point, we want to get its info such as its time, location, and case.

**Comment by chenlica** [comment]
@aishwaryakapse We will use this issue to keep track of the work of collecting info from this site (after you finish your current work).
