### ISSUE TITLE
[CoronavirusTwitterMap] Time series bug

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#748]
## Symptom

Using SQL query to group by data (3/1 ~ 3/20) in database to draw bar chart in google spreadsheet shows the following result.

![coronavirus-group-by](https://user-images.githubusercontent.com/8113414/77233482-e91b3f00-6b64-11ea-915f-e83e76f8e8d5.png)

While our frontend time series bar chart shows the following result.

![coronavirus-time-series](https://user-images.githubusercontent.com/8113414/77233498-094afe00-6b65-11ea-8ad3-1075a68c6b69.png)

They are not consistent.

**Comment by sophiewu6** [comment]
I did some experiments on my local stack, but I can't seem to find any issues.

SQL query results
<img width="600" alt="Screen Shot 2020-03-22 at 12 12 48 AM" src="https://user-images.githubusercontent.com/32754302/77244457-24a02280-6bd2-11ea-8878-02f8164e4632.png">

frontend time series results
<img width="64" alt="Screen Shot 2020-03-22 at 12 14 28 AM" src="https://user-images.githubusercontent.com/32754302/77244460-25d14f80-6bd2-11ea-833d-84c60e26b606.png">

They seem consistent with each other

**Comment by baiqiushi** [comment]
@sophiewu6 Thank you for the update.
I just replaced the `sample.adm.gz` file in the [http://cloudberry.ics.uci.edu/img/coronavirus-tweets/sample.adm.gz](http://cloudberry.ics.uci.edu/img/coronavirus-tweets/sample.adm.gz) to be as the same as our production server. Please try this data to see if you can find something. BTW, to use this new data, you need to change the `endData` in application.conf. Thanks.

**Comment by sophiewu6** [comment]
After replacing the sample.adm.gz file, this is what I got.

SQL query result:
<img width="603" alt="Screen Shot 2020-03-22 at 10 33 58 AM" src="https://user-images.githubusercontent.com/32754302/77256017-cce0d600-6c28-11ea-8546-28b27674b933.png">

frontend time series result:
<img width="175" alt="Screen Shot 2020-03-22 at 10 34 16 AM" src="https://user-images.githubusercontent.com/32754302/77256024-d5391100-6c28-11ea-802c-d3ce854488ad.png">

They still look consistent to me.

However, my local frontend time series looks different from the time series bar on https://coronavirustwittermap.ics.uci.edu/. It seems like the total number of tweets are also different.

local:
<img width="191" alt="Screen Shot 2020-03-22 at 10 37 14 AM" src="https://user-images.githubusercontent.com/32754302/77256072-247f4180-6c29-11ea-9c33-75d875848372.png">
coronavirusmap demo:
<img width="212" alt="Screen Shot 2020-03-22 at 10 37 08 AM" src="https://user-images.githubusercontent.com/32754302/77256083-33fe8a80-6c29-11ea-8e44-3605c293e924.png">

This is what I think: on the demo, for some reason, it only loaded partial coronavirus dataset. But currently I have no idea what may cause this issue.

**Comment by baiqiushi** [comment]
Oh, I see. This might due to some problem of our view maintenance.

**Comment by baiqiushi** [comment]
OK. The real reason is #762
