### ISSUE TITLE
[CoronavirusTwitterMap] Data Collection Brainstorming

### ISSUE THREAD

**Issue by JosephZheng1998** [ISG-ICS/cloudberry#751]
Brainstorming ideas for useful data to display on Coronavirus Twittermap alongside cases and tweet count.

**Comment by chenlica** [comment]
@JosephZheng1998 add a screenshot of the choropleth map to show where we want to add the info.

**Comment by JosephZheng1998** [comment]
We will add the info on the tab shown in the screenshot.

<img width="832" alt="image" src="https://user-images.githubusercontent.com/45022002/77238646-6a87c700-6b8f-11ea-9615-c4a1d97b70ce.png">

**Comment by JosephZheng1998** [comment]
I think the data that are obviously useful are death count and recovered count, which can be pulled from the JHU COVID-19 website.

**Comment by JosephZheng1998** [comment]
We can also add suspected cases alongside confirmed cases. I think hospital count can also be a good data because it is indicative of an area's medical resources.

**Comment by Yicong-Huang** [comment]
please refer to #746 for more on this topic. thanks!

**Comment by baiqiushi** [comment]
Low priority.
