### ISSUE TITLE
Add a query-caching module on TwitterMap server

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#761]
For each query sent from the UI, cache the query results on the TwitterMap server.  Invalidate it after some time (e.g., 5 mins). This method can reduce the number of queries to Cloudberry.

**Comment by Yicong-Huang** [comment]
@chenlica just saw this now. We did not discuss this today, is it still needed for now?

**Comment by baiqiushi** [comment]
Done
