### ISSUE TITLE
Big Data Transfer Statistics

### ISSUE THREAD

**Issue by WANGJIEKE** [ISG-ICS/cloudberry#766]
I built a server with [Play Framework](https://www.playframework.com/) and a front-end web page with [deck.gl](https://deck.gl/), and tried three different methods for data transfer, HTTP with JSON, HTTP with binary response body, and WebSocket. The fastest method is HTTP with binary response body.

I also tested the performance of HTTP with binary response body under two different network settings, transferring within same machine and between two machines in same local network.

![Plot](https://user-images.githubusercontent.com/21030118/77393848-2ba66c80-6d5b-11ea-8c3a-ab327793f5dc.png)

**Comment by baiqiushi** [comment]
Not needed anymore.
