### ISSUE TITLE
Frontend layout change

### ISSUE THREAD

**Issue by sophiewu6** [ISG-ICS/cloudberry#769]
1. Currently, the map choose button is not obvious and clickable enough. Plan to move it to the left and make it vertical.
<img width="1110" alt="Screen Shot 2020-03-24 at 11 46 37 AM" src="https://user-images.githubusercontent.com/32754302/77464926-27169e00-6dc5-11ea-8ff3-6fe2cb7fc255.png">

2. Add the total number of confirmed, recovered, and death cases in the US.

**Comment by Yicong-Huang** [comment]
@sophiewu6 please link the PRs that address this issue.
