### ISSUE TITLE
Evaluation of BEAST

### ISSUE THREAD

**Issue by Leoluo0320** [ISG-ICS/cloudberry#806]
### Overview
This issue aims to evaluate basic functions of BEAST, which is a system for Big Exploratory Analytics on Spatio-Temporal data. It supports visualizing data through data index, image index, and adaptive index. The easiest way to use BEAST is through a command-line interface.

### Prerequisites
- Spark: The system needs command “spark-submit”
- Maven: Used for compiling
- Apache Hadoop: Used for compiling
- Oracle JDK 8: Used for compiling
*versions need to be compatible

### Specification of Machine Used
CPU: Intel Core i7-7700HQ
RAM Size: 16GB
Hard Disk: 256GB SSD

### Input Format
- CSV file containing data in the format of point/rectangle. Need to provide (xcoordinate, y_coordinate) for point and (x1coordinate, y1coordinate, x2coordinate, y2coordinate) for rectangle
- GeoJSON file containing features with geometries and attributes
- Esri shapefile (.shp+ .shx+ .dbf files) or a .zip file with these files
- R-tree index

### Analysis of Input Data
To get some basic information of input data, users can use the command “beast summary” provided by BEAST. It will return information such as the size of input data, number of features, number of points, geometry type, attributes, and so on. Below is an example of using the command and the corresponding output.

Command:
![image](https://user-images.githubusercontent.com/45347246/84535478-bb93ec80-aca0-11ea-9ff4-7311ced452f5.png)

Output:
![image](https://user-images.githubusercontent.com/45347246/84535521-ce0e2600-aca0-11ea-9736-1a76f199aab9.png)

### Visualization Output
To visualize the input data, users can use the command “beast mplot” provided by BEAST. There are three ways to build the index for visualization, i.e. image index, data index, and adaptive index.

***Some Important Parameters**
levels: Number of zoom levels for visualization. Default is 7
threshold: The threshold for classifying tiles as image tiles or data tiles while building 
                 index. If the size of a data tile is greater than the threshold, it will be 
                 considered as an image tile

**1. Image Index**
To visualize the data using the image index, users can simply set the “threshold” parameter to 0, which means all data will be preprocessed as image tiles. Image tiles will be saved in an output folder named by the user. By using the image index, users can view the data through the index.html file in the folder. Below is an example of an output folder and visualization of data.

Output folder:
![image](https://user-images.githubusercontent.com/45347246/84535745-3ceb7f00-aca1-11ea-9cf6-e0d0ad7f09ac.png)

Visualization:
![image](https://user-images.githubusercontent.com/45347246/84535768-470d7d80-aca1-11ea-8ec2-8fa87ef38753.png)

**2. Data Index**
To visualize the data using data index, users can just set the “threshold” parameter greater to the number of the records. The number of records can be easily get using the “beast summary” command mentioned previously. By purely using the data index, all images will be produced on the fly so users will need to wait for some time to see the image. The waiting time depends on how many records the image contains. Since the images are produced on the fly, users need to connect to a server that can generate images according to the data. BEAST provides command “beast server port:port_number” for generating image tiles on the fly. Below is an example of the command used, output folder, and visualization.

Output folder:
![image](https://user-images.githubusercontent.com/45347246/84535822-660c0f80-aca1-11ea-96a1-9b5a88c50c3b.png)

Visualization while waiting:
![image](https://user-images.githubusercontent.com/45347246/84535842-6efce100-aca1-11ea-9d74-fe7031fa29bc.png)
Part of images for this zoom level is generated:
![image](https://user-images.githubusercontent.com/45347246/84535857-7a500c80-aca1-11ea-9005-fc7873f84a1c.png)
All images are generated:
![image](https://user-images.githubusercontent.com/45347246/84535869-81771a80-aca1-11ea-93c4-472ad8dec4dd.png)

**3. Adaptive Index**
The adaptive index is a combination of image and data index. By using an adaptive index, it will use data index for those that are quick to generate image tiles on the fly, which will save some time for preprocessing image tiles. The boundary for image and data index is decided by the “threshold” parameter. Below is the idea of the adaptive index and an example of the output folder.

The idea of Adaptive Index:
![image](https://user-images.githubusercontent.com/45347246/84535936-a66b8d80-aca1-11ea-892a-a14e99f18490.png)

Output folder:
![image](https://user-images.githubusercontent.com/45347246/84535972-bc794e00-aca1-11ea-980a-35c72fca1b6e.png)

***Optimized Multilevel Plot**
BEAST system provides a way to build an optimized multilevel plot by creating an index (pyramid of images) for the input first. It can be done using the command “beast index” provided by the system. It supports indexes such as zcurve, grid, rsgrove, rstreebb. Below is an example of an index folder and output folder.

Index Folder:
![image](https://user-images.githubusercontent.com/45347246/84536035-d6b32c00-aca1-11ea-8546-9f60e3910a1b.png)

Output Folder:
![image](https://user-images.githubusercontent.com/45347246/84536051-e03c9400-aca1-11ea-90a8-49a393bce0ed.png)

### Analysis of Different Index
Below is the basic information of input files for testing
![image](https://user-images.githubusercontent.com/45347246/84536087-f3e7fa80-aca1-11ea-8688-3e66a1bcd0c3.png)

Below is a table of 3 CSV input files and corresponding sizes of the output folder.
![image](https://user-images.githubusercontent.com/45347246/84536105-fd716280-aca1-11ea-8247-63232e7c307d.png)

From the tables above, it is obvious that the sizes of image indexes and optimal indexes are much smaller than the input size; sizes of data indexes are about the same as input size; the performance of adaptive indexes mainly depends on the input data and threshold.

**Image Index**
For image index, image tiles for all zoom levels are preprocessed for future visualization. Each image tile is about 1 or 2 KB. For every image tile, if users increase zoom level by 1, the tile at the previous zoom level will be split into 4 tiles so more details can be seen. If data is sparse, for example, the NE_airports_index shown in the table, there will be some blank tiles while zooming in. BEAST will automatically delete these image tiles to save the space.

It is very expensive for BEAST to purely using image index because of the limited memory. As the zoom level increases, the cost of both time and memory will increase greatly. Below is a chart for different zoom levels for each dataset.
![image](https://user-images.githubusercontent.com/45347246/84536174-1f6ae500-aca2-11ea-964b-b8443db2284f.png)

From the table above, when the zoom level increases by 1, the time and size of the output folder become 2 times larger. For 10m_tweets dataset, it is even impossible to generate all images for zoom level above 7 since Java throws OutOfMemory Exception.

**Data Index**
For data index, it produces all the image tiles for visualization on the fly. When the dataset is small, everything works fine. However, when the number of records and zoom levels increases, users will have to wait for a long time to see the visualization of the data, which is bad user experience.

**Adaptive Index**
According to the analysis of the image index and data index, there is a memory-time tradeoff between these two kinds of indexes. Thus, if we want to view more zoom levels with limited memory storage, we can use the adaptive index, which will produce data tiles smaller than the threshold. Below is an example of using an adaptive index to increase the zoom level.
![image](https://user-images.githubusercontent.com/45347246/84536243-40333a80-aca2-11ea-8d67-6f2135ffbb78.png)

From the table above, we can find out by increasing the threshold to 5m bytes and 10m bytes, users can view zoom level 8 and 9, which cannot be achieved by purely using image index. Also, by comparing threshold 5m bytes and 10m bytes, we can find the bigger the threshold is, the larger the size of the output will be. This is because when the threshold increases, more data will be generated as data files, which is much larger than image tiles. If the threshold is too large, some data tiles will be very large that users need to wait for a long time for the image tiles produced on the fly.

### Conclusion
- Image index will spend more time on preprocessing the image tiles. It will take up a large amount of memory when it is processing. But when it finishes generating image tiles, the output is small.
- Data index takes up larger disk space than image index. It produces image tiles for visualization on the fly. When the number of zoom levels is large, it will take a long time to generate the image tiles.
- Adaptive index enables users to make a trade-off between waiting time and memory. By setting the parameter "threshold" to an appropriate value, users are able to view more zoom levels with limited memory storage.

**Comment by baiqiushi** [comment]
Done.
