### ISSUE TITLE
Compare MapD/Omnisci and Cloudberry

### ISSUE THREAD

**Issue by chenlica** [ISG-ICS/cloudberry#810]
### Purpose: 
compare two approaches to big data visualization and analytics

- MapD/OmniSci
- Cloudberry

### Instructions

- [x] setup Cloudberry: https://github.com/ISG-ICS/cloudberry/wiki/quick-start
- [x] setup latest Asterixdb: https://github.com/apache/asterixdb
- [x] setup OmniSci: https://github.com/omnisci/omniscidb
- [x] convert JSON file to CSV and ingest the data in OmniSci
- [x] convert the queries to omnisci syntax: shorturl.at/ILM25
- [ ] evaluate the performance on AWS instance

A related issue done earlier: https://github.com/ISG-ICS/cloudberry/issues/685

**Comment by annielya** [comment]
1. polished results https://docs.google.com/spreadsheets/d/1hcXDiz1w1jMk0R2sgsujHMXC8uJDSDwBVSNtn6Mxsvg/edit#gid=1560495851

**Comment by baiqiushi** [comment]
Done.
