### ISSUE TITLE
Map Tile Provider Deprecated

### ISSUE THREAD

**Issue by Yicong-Huang** [ISG-ICS/cloudberry#811]
The default map tile provide is no longer in service. Now it returns this error message:

```{"message":"Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"}```

Now the frontend looks like this:
![Screen Shot 2020-10-05 at 7 13 14 PM](https://user-images.githubusercontent.com/17627829/95151784-68a6df00-0740-11eb-9dab-2c682d0b2393.png)

__This affected both CoronavirusTM and Twittermap projects.__

**Comment by rajredmart** [comment]
@Yicong-Huang Did you found any solution for this ? Looks like mapbox stopped this API.

**Comment by Yicong-Huang** [comment]
> @Yicong-Huang Did you found any solution for this ? Looks like mapbox stopped this API.

Yes we are still looking for alternatives.
