### ISSUE TITLE
Real-time Tweet not working

### ISSUE THREAD

**Issue by Yicong-Huang** [ISG-ICS/cloudberry#812]

**Comment by baiqiushi** [comment]
The hacky way to retrieve real-time tweets is deprecated. Change the `useDirectSource` in `application.conf` to be false to disable it.

**Comment by Yicong-Huang** [comment]
Do this mean we don’t have live tweet in both websites?

**Comment by Yicong-Huang** [comment]
Oh my bad did not see the context.
