### ISSUE TITLE
Collecting Zika Related Information

### ISSUE THREAD

**Issue by JavierJia** [ISG-ICS/cloudberry#86]
We want to collect as much information about Zika as possible.  The following are related sources:

- [x] Twitter https://github.com/ISG-ICS/cloudberry/issues/65
- [x] ProMED: https://github.com/ISG-ICS/cloudberry/issues/66 , http://www.promedmail.org/
- [x] ProQuest Newsstand: https://github.com/ISG-ICS/cloudberry/issues/67 , http://www.proquest.com/products-services/globalnewsstream.html
- [x] Dow Jones Factiva: https://github.com/ISG-ICS/cloudberry/issues/68 , http://www.dowjones.com/products/product-factiva/
- [x] Healthmap: https://github.com/ISG-ICS/cloudberry/issues/74 , http://www.healthmap.org/zika/#timeline 

The following Google Drive includes references related to Zika: https://drive.google.com/folderview?id=0B6pJr3rz2MCGTTVrWm12MFJ2ZnM&usp=sharing

**Comment by JavierJia** [comment]
@chenlica  I'm thinking it's better to use the `wiki` as a user-oriented message board instead of the dev-oriented. In this way, the user won't be puzzled in tons of information. We can use issues to describe the work and keep the internal working progress either in google drive or in issue list, only put it to `wik`i if it necessary to let users know. 

Do you agree? 😄

**Comment by chenlica** [comment]
Sure!  I remember I created a wiki for this task, but couldn't find it any more. Weird.  Please go ahead.  I still prefer to have one issue for each data source since it's really a task, and wiki is used for documentation.

**Comment by JavierJia** [comment]
Sorry, I copied it here, and deleted it by accident.... 😢

**Comment by JavierJia** [comment]
I would like to use the wiki as an `external` documentation. For the intermediate result or docs, I still want to organize them using google drive, not wiki.

**Comment by chenlica** [comment]
I am OK with using Google Drive with the following suggestions: (1) Having a "hub wiki" with pointers to those files so that we can find info easily; and (2) Change the owners of the google drive files to the "group gmail account".  We are using that practice for TextDB.

**Comment by JavierJia** [comment]
Will follow the same principle 😄
